### PR TITLE
add workaround for inserting space on autocomplete on Mac

### LINKED ISSUE #1323: CLI bash auto complete should add space at the end of a completed command
The CLI provides a bash auto completion profile but the completion does not add a space at the end of a completed command. This is not consistent with usually shell completion.

### PR DESCRIPTION
**Pull request by csantanapr**
Closes #1323

### CODE REVIEW

**Comment by csantanapr** [comment]
something weird with travis builds timing out after hours

**Comment by rabbah** [comment]
works for me on mac.

**Comment by dubeejw** [comment]
@mdeuser, perhaps you can speak to Windows on this issue.

**Comment by mdeuser** [comment]
@dubeejw - sure.  can you give me a specific example to try out.  the command auto completion seems to work fine on windows/vagrant/ubuntu for me, but i'm sure there's some subtlety..

**Comment by csantanapr** [comment]
Yeah it works on Linux and Windows without the workaround

**Pull request merged**
