### PR TITLE
Treat action code as attachments for created/updated actions

### PR DESCRIPTION
**Pull request by dubee**
Supersedes https://github.com/apache/incubator-openwhisk/pull/2847.

### CODE REVIEW

**Comment by markusthoemmes** [comment]
@dubeejw can we close this PR? You can setup travis on your own repository if you want to have full travis coverage.

**Comment by dubee** [comment]
@rabbah, @markusthoemmes, a cache concurrency test fails on this one. I have figured out the failure is due the need of two DB writes for saving attachments. Where the first write is for the DB document and the second write is for the DB document attachment. 

When only caching Java actions as done in https://github.com/apache/incubator-openwhisk/pull/2855 and implementing the same concurrency test for Java actions, the test will fail as well.
```

Failure output shown here. The test fails because `update` does two writes as stated above, so a concurrent `get` request can fail as `update` does not finish as quickly for attachments.
```
whisk.core.database.test.CacheConcurrencyTests > the cache should support concurrent CRUD without bogus residual cache entries, iter 1 FAILED
    org.scalatest.exceptions.TestFailedException: update+get: failed for testy4 404 was not equal to 200
```

**Comment by dubee** [comment]
I suppose another option would be to change the test to accept a 200 or 404 from the `get` requests.

**Comment by dubee** [comment]
Closing https://github.com/apache/incubator-openwhisk/pull/2847 in favor of this PR as it was easier to rebase with the merged caching changes.

**Comment by dubee** [comment]
@chetanmeh, do you think these changes will be useful in the future?

**Comment by chetanmeh** [comment]
@dubee Yes this would be useful as document size limitation is impacting nodejs kind also for us. So would like to convert all types to attachments. With support for Inlined attachments #3709 switching to attachment should not have negative impact on small functions.

**Comment by chetanmeh** [comment]
@dubee  Do you plan to work on this otherwise I can look into it. Given recent changes in master the `ArtifactStore` does not make use of attachmentName attribute from manifest. So was thinking to do away with manifest entry for name attribute.

For attachment type I am not sure - For e.g. if its a simple code snippet then type can be `text/plain` otherwise if its a zip (say js code packaged as zip) then it would be `application/octet-stream`.

Further with inlining support now we can **always** store the code for all kinds as attachments by design and let `ArtifactStore` inline the binary if its small. So no need to different between attachment for various kinds

**Comment by chetanmeh** [comment]
@dubee Ping

**Comment by chetanmeh** [comment]
PR #3945 supersedes this one

**Pull request closed without merging**
