### PR TITLE
Preserve rule status on update according to #1840.

### LINKED ISSUE #1840: Updating a rule changes its status to inactive
If you edit a rule, it becomes disabled in OpenWhisk. It should not change the status of the rule.

### PR DESCRIPTION
**Pull request by kevinlai**
Resolves #1840 
Ran PG (#695)

### CODE REVIEW

**Comment by rabbah** [comment]
LG but needs tests.

**Comment by rabbah** [comment]
@mdeuser this would be a good one to pick up also for the controller - this fix may be correct but is lacking test coverage.

**Comment by rabbah** [comment]
Closing for #3254.

**Comment by markusthoemmes** [comment]
@rabbah wanted to close I think.

**Pull request closed without merging**
