### PR TITLE
Reduce invoker health action memory limit to 128MB

### PR DESCRIPTION
**Pull request by SugandhaAgrawal**
## Description
In order to keep the Invoker health test's action with a minimalistic memory, the value of memory limit is changed from the standard memory config to the minimum available memory. This helps in consuming the resource in minimal way possible and would suppress the Rescheduling run message occurrence due to health test.

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [x] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [x] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by csantanapr** [comment]
Should we use this opportunity to set the default min to 64MB?

**Comment by sven-lange-last** [comment]
@csantanapr Reducing the general limit from 128 MB to 64 MB would potentially mean a higher number of concurrent actions per invoker when keeping the same amount of action memory on the invoker. As a consequence the CPU consumption may double. Increasing the potential CPU consumption on the one hand may also require CPU capping for action on the other hand.

At the moment, the Docker container implementation does not support CPU capping. We should definitely look into this topic.

**Comment by csantanapr** [comment]
I had the impression we were already calculating the cpu share by using the fraction of the memory limit proportion since we currently pass the “--cpu-shares” flag. 

So Indont follow, less memory would mean more actions, higher density per invoker, each action with small men gets smaller cpu share.

**Comment by sven-lange-last** [comment]
CPU shares just makes sure that a cgroup receives a minimum amount of CPU if and only if all CPUs are 100% loaded. It has no influence on the maximum CPU share a single cgroup receives.

See https://www.kernel.org/doc/Documentation/cgroup-v1/cgroups.txt and https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt.

**Comment by cbickel** [comment]
@csantanapr I think there are more problems that arise on going down to 64MB (As Sven already mentioned). But the current change will pick up the new minimum value immediately on changing this. So I'll merge this PR as it is for now.

**Pull request merged**
