### PR TITLE
Adjust invoker playbook to pull docker images when a prefix and tag is specified.

### PR DESCRIPTION
**Pull request by rabbah**
## Description

The invoker playbook ignores an image prefix when pre-fetching the blackbox images. This patch splits the blackbox tasks so that ones that do not have a prefix may be skipped (as today), but those that specify a prefix are always pulled, using the specified prefix in the image name.

Fixes https://github.com/apache/incubator-openwhisk/issues/3679.

## Related issue and scope

- [x] I opened an issue to propose and discuss this change (#3679)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [x] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [x] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [x] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by rabbah** [comment]
relabelling `wip` to rework the pull/tag bits... maybe experiment with moving these bits into the invoker instead.

**Comment by rabbah** [comment]
@csantanapr made the changes we discussed on Slack to disentangle the image pulls from the docker registry.

**Comment by rabbah** [comment]
@dgrove-oss I think you'll need to review this now as its scope as widened a little. I did checked the kube deployment and I think the change is compatible but will appreciate your input.

With the latest changes, runtime images are pulled from the given docker registry for _runtimes_ (default is dockerhub) which is now allowed to be different from the docker.registry; the latter is now strictly used for the system components. 

It is possible to skip the pulling of images entirely:
```
    ansible-playbook -i environments/local invoker.yml -e 'skip_pull_runtimes=true'
```

or with `redo`
```
   redo invoker -e"skip_pull_runtimes=true" 
```

**Comment by rabbah** [comment]
@ddragosd this may also be relevant to docker-compose although I haven't checked that deployment yet.

**Comment by rabbah** [comment]
Some caveats with this change: building new runtime images for local testing means:

* locally tagged image used in the runtimes manifest may be used without pushing to docker hub, provided the `skip_pull_runtimes` is enabled
* if `skip_pull_runtimes` is enabled but the runtimes manifest includes images that are not already pulled, they may fail in the invoker, or be pulled on the first `run`.

**Comment by dgrove-oss** [comment]
Looks like this would be straightforward for kube.  We'd need to update the copies of runtime.json and tweak values.yaml and the various deployment templates for the pods to reflect the change in environment variables.

**Pull request merged**
