### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by underwoodb-sd-ibm**
Updated the main README file to reflect the need for an ssh client to be installed on Windows machines.

### CODE REVIEW

**Comment by dubeejw** [comment]
@underwoodb-sd-ibm, looks like you have CLI changes in here. Assuming this should just contain the doc update?

**Comment by underwoodb-sd-ibm** [comment]
There was only supposed to be a documentation change, yes. My apologies, I will work on fixing this pull request. :/

**Comment by dubeejw** [comment]
@underwoodb-sd-ibm, is this PR still valid?

**Comment by rabbah** [comment]
why is this PR separate from the #2326 pr? I suggest merging.

**Comment by underwoodb-sd-ibm** [comment]
@rabbah, @dubeejw: Requested changes have been made, my apologies for not attending to this sooner.

**Pull request merged**
