### PR TITLE
add cron npm package

### PR DESCRIPTION
**Pull request by jasonpet**

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Why do we add this? A brief description in the PR would be helpful. You'll also need to update documentation.

**Comment by csantanapr** [comment]
@markusthoemmes 

It's related to this https://github.com/apache/incubator-openwhisk-package-alarms/issues/63

i.e use the cron package to validate if the pattern is valid early in the feed action, this is also required for the new redundant work were action is going to insert new trigger into DB.

**Comment by csantanapr** [comment]
@jasonpet update doc here: https://github.com/apache/incubator-openwhisk/blob/master/docs/reference.md#javascript-runtime-environments

**Comment by rabbah** [comment]
Does it make sense to use a zip for the alarm action rather that put it in the runtime?

**Comment by csantanapr** [comment]
yes it could be done with a zip action

**Comment by jasonpet** [comment]
will do it as a zip

**Pull request closed without merging**
