### PR TITLE
Multiple fixes to apiv1swagger.json

### PR DESCRIPTION
**Pull request by larandersson**
## Description
This PR fixes the following issues with the Swagger specification:

1. Fixed 2 typos that refer to non-existing response 'TooManyRequsts'
2. Updated description of PUT method for rule
3. Updated description of PUT method for trigger
4. Created new definition ActivationBrief
5. Changed response type for GET activations to refer to ActivationBrief instead of EntityBrief, which didn't match the actual response
6. Added attribute statusCode to definition ActivationBrief and Activation
7. Modified description of GET activations (#2271)
8. Added operationId to GET activation logs and result (#318)
9. Removed the init attribute from the ActionExec definition (#4201)
10. Use of 2 spaces for indentation, which is the default when working with the Swagger editor, instead of the four spaces previously used

## Related issue and scope
- [x] Doc issue with "Get activation IDs" (#2271)
- [x] In Swagger file, operationId is missing for activation logs and results (#318)
- [x] Update swagger for action put #4201

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [x] Documentation

## Types of changes

- [x] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [ ] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by larandersson** [comment]
Travis build is failing multiple tests:
```
org.apache.openwhisk.core.containerpool.test.ContainerProxyTests > ContainerProxy should stay in Running state if others are still running FAILED
    java.lang.AssertionError: assertion failed: expected:  but got unexpected message Transition(Actor[akka://ContainerProxys/system/testActor-10/$g#670589197],Running,Ready)

org.apache.openwhisk.core.containerpool.test.ContainerProxyTests > ContainerProxy should complete the transaction and reuse the container on a failed run IFF failure was applicationError FAILED
    java.lang.AssertionError: assertion failed: expected class akka.actor.ActorRef, found class akka.actor.FSM$Transition (Transition(Actor[akka://ContainerProxys/system/testActor-10/$g#670589197],Ready,Running))

org.apache.openwhisk.core.containerpool.test.ContainerProxyTests > ContainerProxy should complete the transaction and abort if container creation fails FAILED
    java.lang.AssertionError: assertion failed: expected class akka.actor.ActorRef, found class org.apache.openwhisk.core.containerpool.NeedWork (NeedWork(WarmedData(ContainerId(testcontainer),invocationSpace,ExecutableWhiskAction/actionSpace/actionName@0.0.1,2019-02-18T09:26:42.302Z,1)))
```
...and more

Surely not because of changes to the Swagger??

**Comment by rabbah** [comment]
The first commit is from another PR - should be dropped here?

**Comment by rabbah** [comment]
Note to reviewers: Use `w=1` to ignore white space diffs. https://github.com/apache/incubator-openwhisk/pull/4294/files?utf8=%E2%9C%93&diff=unified&w=1

**Comment by larandersson** [comment]
@rabbah Sorry about the extra commit, that was for the other PR (#4295). Removed that one from this PR.

**Pull request merged**
