### PR TITLE
add support for email address scan to scanCode.py

### PR DESCRIPTION
**Pull request by domdom82**
Added feature to scan for given email address regex patterns. Useful if you want to avoid internal company or private emails in the code.

Greeting from SAP, keep up the good work! :-)

### CODE REVIEW

**Comment by markusthoemmes** [comment]
For old times sake I tried to find an indentation error. Could'nt find one :+1: 😬 

@mrutkows are we moving scanCode out of this repo or do we keep adding stuff here?

**Comment by mrutkows** [comment]
@markusthoemmes @domdom82 we are moving to use it out of the "incubator-openwhisk-utilities" repo.  and any changes made here need to instead be made there.  I have a PR "wip" now... https://github.com/apache/incubator-openwhisk/pull/2325 to remove scancode in the main openwhisk repo. and use from new location.

**Comment by rabbah** [comment]
hey @domdom82 - do you mind opening this pr against this repo since this is the eventual home for scan code https://github.com/apache/incubator-openwhisk-utilities?

**Comment by mrutkows** [comment]
@rabbah @domdom82 I am happy to move the code myself if I would not offend anyone.

**Comment by mrutkows** [comment]
Upon looking at the code, it appears this is not strictly an "email" scan; it is a general regex. "match" and it did not work unless the "match" appeared first on the "line".  I'm moving the "intent" of this code to the new "utilities" version of scancode (i.e., in https://github.com/apache/incubator-openwhisk-utilities repo.) .   

As part of this, I am updating the code to permit a general "regex" scan and change the "Email filter" to a general "regex filter".  In addition, I will use the "search" function to allow matching regardless of appearance within a line.  Also, will add tests...

**Pull request closed without merging**
