### PR TITLE
bump nodejs6 from 6.9.1 to 6.11.3

### PR DESCRIPTION
**Pull request by jeremiaswerner**

### CODE REVIEW

**Comment by rabbah** [comment]
this or https://github.com/apache/incubator-openwhisk/pull/2078 is a duplicate.

**Comment by csantanapr** [comment]
I thought the discussion in the dev list https://lists.apache.org/thread.html/e882dd05f23dd7d313b00f520e7cb3c362636bba6a5d9112ec97a8a2@%3Cdev.openwhisk.apache.org%3E

Was leave nodejs:6 at `6.9.x` and if we want a new version to create new kinds at the minor level `6.11.x` resulting in a new runtime and kind `nodejs:6.11` with the npm packages updated to the latest this allows to users/customers to have a bit of time to move from 6.9 to 6.11.

Allowing them to test in the new kind, with the new packages, and any node binary modules to be recompile for node 6.11.x

**Comment by jeremiaswerner** [comment]
@csantanapr I agree and close this PR.

**Comment by rabbah** [comment]
thanks @jeremiaswerner and @csantanapr - should we wait to add new kinds until we've factored out the runtimes so we have a better build time story?

also, should #2078 be closed then?

**Pull request closed without merging**
