### PR TITLE
Reuse namespace in the Python 3 action runtime

### PR DESCRIPTION
**Pull request by bjustin-ibm**
This allows actions to set/retrieve global variables as an additional optimization during container reuse.

### CODE REVIEW

**Comment by bjustin-ibm** [comment]
🔵 PG1 1847

**Comment by markusthoemmes** [comment]
Considered adding a test?

**Comment by bjustin-ibm** [comment]
> looks good, namespace becomes the global object carried across activations (maybe it should be called something else?).

How about... `global_context`?

**Comment by bjustin-ibm** [comment]
🏃 PG1 1853

**Pull request merged**
