### PR TITLE
Remove Consul from "The Internal flow of processing" section diagram in about.md

### PR DESCRIPTION
**Pull request by shazron**
All logos are vectors in the source file.

## Description

This changes the "Internal flow of processing" diagram in About.md since Consul has been removed. Tested by previewing the markdown, and added the source file as well (draw.io source file, draw.io is open sourced Apache-2.0, hosted as well as offline available).

## Related issue and scope

- [X] I opened an issue to propose and discuss this change (#3207)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [X] Documentation

## Types of changes

- [X] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [X] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [ ] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [X] I updated the documentation where necessary.

### CODE REVIEW

**Comment by shazron** [comment]
Not sure why one of the builds in the build matrix failed, this is just a doc change...

**Comment by markusthoemmes** [comment]
@shazron should be fine after #3642 is merged.

**Comment by csantanapr** [comment]
Ah ok @shazron different readme problem, scancode changed and is out of this repo

**Comment by shazron** [comment]
Rebased. All checks pass.

**Comment by csantanapr** [comment]
Sweet 👍 @shazron

**Pull request merged**
