### PR TITLE
Replace count suffix with counter

### PR DESCRIPTION
**Pull request by SugandhaAgrawal**
Replace the `count` suffix for metrics by `counter`.

## Description

Suffix `count` has been used in OpenWhisk code for recording metrics - gauges and histogram which as per definition of graphite data source corresponds to the max value by aggregation. This has been reporting incorrect information. The recommendation is to use any other suffix other than `count`, `max` and `min`, if actual count at given time is the expected output hence changing it in logging logic to `counter`.

- The data being represented for eg in - Grafana would be reported correctly. Today, due to the use of `count`, the value is aggregated by `max`.
- The graphical representation of the `count` metrics would need adaption.

## Related issue and scope
 
- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [x] General tooling
- [x] Documentation

## Types of changes

- [x] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [x] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [x] I updated the documentation where necessary.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/OpenWhisk-Playground/93/
Test FAILed.
Test FAILured.

**Comment by chetanmeh** [comment]
> Suffix count has been used in OpenWhisk code for recording metrics - gauges and histogram which as per definition of graphite data source corresponds to the max value by aggregation

@SugandhaAgrawal As this would be a breaking change can you provide some reference document link which explains this convention

**Comment by SugandhaAgrawal** [comment]
Reference to support the use of `count` suffix for `max` aggregation is here:

- https://github.com/graphite-project/carbon/blob/master/conf/storage-aggregation.conf.example
- https://answers.launchpad.net/graphite/+question/286462

**Comment by SugandhaAgrawal** [comment]
@chetanmeh - Please have a look at the references provided. TIA

**Pull request merged**
