### PR TITLE
Support alternative path for python in whiskprops

### PR DESCRIPTION
**Pull request by tz70s**
By default, the path of python2.7 is located at `/usr/bin/`
instead of `/usr/local/bin/`. Since folks may desire to use homebrew
installation and the path _might_ be relocated at `/usr/local/bin/`. Support path
from `/usr/bin` both is better to avoid python3 override the default
`python` without any penalty.

Signed-off-by: Tzu-Chiao Yeh <su3g4284zo6y7@gmail.com>

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

Not sure the small change is needed to open an additional issue? Didn't find similar issue, though.

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [x] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [x] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by rabbah** [comment]
This change is ok but I'm wondering if we actually need this still. I a few scripts are still in python (wskdamin, wskdev) but may be python 3 compatible. The reason for python 2.7 was the previous version of the wsk CLI which wasn't python 3 ready.

**Comment by tz70s** [comment]
In my experience, `wskadmin` is not python 3 compatible. For example, `httplib` is particular a python2.7 name, `http.client` in python3. 
This makes me meet some problems under #3474.

However, the `wskadmin` script currently is fined bc I'm not sure `python2.7` binary is available on all platform. 
But in the `WhiskProperties` case, it might be worth to provide the path additionally.

**Comment by tz70s** [comment]
@rabbah , this helps me a lot, thanks!

**Comment by tz70s** [comment]
@rabbah , I found that there's plenty of places that should not be compatible.
If we really desire to have compatibility, as you mentioned, I think I can work on 2to3 scan associated with a travis build for checking all python 2, 3 code got passed. Should we have an additional branch on here for a visible testing result?

**Comment by rabbah** [comment]
+1 python 3 is a decade old :) (@cclauss this will make you happy :)

**Comment by tz70s** [comment]
Additional opinion, I think we can block this pr, once all processes finish.

**Comment by rabbah** [comment]
`wskadmin`, `replicateDbs`, `cleanUpActivations`, and `deleteLogsFromActivations` use the python path in whisk properties.

**Comment by tz70s** [comment]
I've checked for `cleanUpActivations` and `deleteLogsFromActivations` in pending #3483 . I can't successfully tested with `replicateDbs` seems caused by some additional problems in my settings/mac. (It didn't throw any python error, though) Waiting for travis check.

Maybe some additional utilities? i.e. `scanCode` (I'm sure it's not currently compatible)

**Comment by rabbah** [comment]
@cclauss first i'd like to get the code compatible, then we can update the docs to make python 3 the default.

**Comment by cclauss** [comment]
@rabbah I was not talking about which is default.  I was talking about how we discover the path to the executable.

**Comment by rabbah** [comment]
Ah - thanks for clarifying. I'm thinking we can just nuke that method entirely.

**Pull request merged**
