### PR TITLE
update nodejs6 with g++ and other utilities

### LINKED ISSUE #2311: Update nodejs6 runtime with utilities to allow building node_modules binaries
Some npm packages need binaries to be compiled
The nodejs6action should have everything required for an user to use it to build a nodejs action zip.

This is applicable to packages like [ibm_db](https://www.npmjs.com/package/ibm_db)

For example python, make, zip, g++

Errors with node-gyp
```
{ Error: Command failed: node-gyp configure build 
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```
```
{ Error: Command failed: node-gyp configure build --IBM_DB_HOME="$IBM_DB_HOME" --IS_DOWNLOADED=true
gyp ERR! build error
gyp ERR! stack Error: not found: make
```
```
{ Error: Command failed: node-gyp configure build 
make: g++: Command not found
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
```

### PR DESCRIPTION
**Pull request by csantanapr**
Closes #2311

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Have you measured the impact on the image size of this?

**Comment by csantanapr** [comment]
@markusthoemmes  yes

**Comment by csantanapr** [comment]
Before any changes
```
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
nodejs6action            latest              922199356a9b        12 minutes ago      485.4 MB
whisk/nodejs6action      latest              922199356a9b        12 minutes ago      485.4 MB
nodejsactionbase         latest              d608f8e406b1        13 minutes ago      302.7 MB
whisk/nodejsactionbase   latest              d608f8e406b1        13 minutes ago      302.7 MB
buildpack-deps           trusty-curl         5fa514013bea        10 days ago         199.7 MB
```
With node 6.11 and updated packages
```
nodejs6action            latest              53c82b620fb0        6 seconds ago        478.7 MB
whisk/nodejs6action      latest              53c82b620fb0        6 seconds ago        478.7 MB
nodejsactionbase         latest              8f8d36fd5aaf        About a minute ago   302.7 MB
whisk/nodejsactionbase   latest              8f8d36fd5aaf        About a minute ago   302.7 MB
buildpack-deps           trusty-curl         5fa514013bea        10 days ago          199.7 MB
```
Adding g++, make, python, jq
```
REPOSITORY               TAG                 IMAGE ID            CREATED              SIZE
nodejs6action            latest              9414834c6879        About a minute ago   614.1 MB
whisk/nodejs6action      latest              9414834c6879        About a minute ago   614.1 MB
nodejsactionbase         latest              dfca57b2f896        2 minutes ago        435 MB
whisk/nodejsactionbase   latest              dfca57b2f896        2 minutes ago        435 MB
buildpack-deps           trusty-curl         5fa514013bea        10 days ago          199.7 MB
```

**Comment by markusthoemmes** [comment]
As for the general build environment: What do you think about using `buildpack-deps:trusty` instead of `trusty-curl`? I think it has all the build environment packages installed, but I think it'll end up in even larger images.

**Comment by csantanapr** [comment]
I can try, but don't think there is much difference
https://github.com/docker-library/buildpack-deps/blob/af914a5bde2a749884177393c8140384048dc5f9/trusty/curl/Dockerfile

I have to add curl anyway, and don't think we should remove wget if it's already present.

**Comment by csantanapr** [comment]
added git
use the option `--no-install-recommends`
&& rm -rf /var/lib/apt/lists/*
cut the image by 61MB

```
REPOSITORY               TAG                 IMAGE ID            CREATED              SIZE
nodejs6action            latest              0ddcc240e509        4 seconds ago        553.6 MB
whisk/nodejs6action      latest              0ddcc240e509        4 seconds ago        553.6 MB
nodejsactionbase         latest              e088afd40480        About a minute ago   374.5 MB
whisk/nodejsactionbase   latest              e088afd40480        About a minute ago   374.5 MB
buildpack-deps           trusty-curl         5fa514013bea        10 days ago          199.7 MB
```

**Comment by csantanapr** [comment]
I use `npm cache clean` 
this reduce the image by 42MB
```
REPOSITORY               TAG                 IMAGE ID            CREATED              SIZE
nodejs6action            latest              1a96411364db        3 seconds ago        511 MB
whisk/nodejs6action      latest              1a96411364db        3 seconds ago        511 MB
nodejsactionbase         latest              05380536a30d        About a minute ago   374.5 MB
whisk/nodejsactionbase   latest              05380536a30d        About a minute ago   374.5 MB
buildpack-deps           trusty-curl         5fa514013bea        10 days ago          199.7 MB
```

**Comment by markusthoemmes** [comment]
@csantanapr I meant `buildpack-deps:trusty` which contains curl and all the environment already.

**Comment by csantanapr** [comment]
@markusthoemmes I see now
Here is the Docker file for `buildpack-deps:trusty`
https://github.com/docker-library/buildpack-deps/blob/587934fb063d770d0611e94b57c9dd7a38edf928/trusty/Dockerfile

I think this will make it larger, and I want to make it smaller with only the minimum I need.

**Comment by csantanapr** [comment]
This are the results using `buildpack-deps:trusty`
```
REPOSITORY               TAG                 IMAGE ID            CREATED              SIZE
nodejs6action            latest              72baf51c3579        5 seconds ago        690.3 MB
whisk/nodejs6action      latest              72baf51c3579        5 seconds ago        690.3 MB
nodejsactionbase         latest              c1a2c19dde46        About a minute ago   553.8 MB
whisk/nodejsactionbase   latest              c1a2c19dde46        About a minute ago   553.8 MB
buildpack-deps           trusty              4838ed9aeb3f        10 days ago          550.5 MB
```

**Comment by rabbah** [comment]
We really should avoid doing this and instead have another "kind". Whatever we introduce into the base image creates legacy overhead to deal with. We know we need more kinds in general and we have a path to do this more rapidly and cleanly while allowing operators to customize what they offer. I would pursue that path instead.

**Comment by csantanapr** [comment]
closing this one as we are going to work on creating images and kinds for builder/init actions, and keep the the images for invocations small

**Pull request closed without merging**
