### PR TITLE
Wrap producer.send with Future

### PR DESCRIPTION
**Pull request by jiangpengcheng**
Wrap producer.send with Future to make it asynchronous

## Related issue and scope
- [x] I opened an issue to propose and discuss this change (#3458)

## My changes affect the following components
- [ ] API
- [ ] Controller
- [x] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes
- [x] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by rabbah** [comment]
Thanks for this patch. The culprit is `waitOnMetadata` in the `send` method
```
            ClusterAndWaitTime clusterAndWaitTime = waitOnMetadata(record.topic(), record.partition(), maxBlockTimeMs);
```

I generally agree then with the fix. Since now the code would use a Scala future, we can eliminate the callback passed to the Java future and just use `andThen`.

@markusthoemmes @cbickel one of you please also have a look.

**Comment by jiangpengcheng** [comment]
@rabbah you mean like this?:

```scala
Future {
  blocking( producer.send(record) )
} andThen {
  case Success(futureMetadata) =>
    try {
      produced.success(futureMetadata.get)
    } catch {
      case e: ExecutionException =>
        produced.failure(e.getCause)
    }
  case Failure(t) =>
    produced.failure(t)
}
```

As the return type of `producer.send(record)` is a `java.util.concurrent.Future<RecordMetadata>`, do you have any better idea to finish a scala `Promise` with a java `Future`?

**Comment by rabbah** [comment]
Ah. Never mind then. Thanks for trying it out.

**Comment by dubee** [comment]
PG4 1514 🚤

**Comment by dubee** [comment]
PG5 1514 🔵

**Comment by dubee** [comment]
PG is good on this one. Will waiting until @cbickel or @markusthoemmes take a look before merging.

**Pull request merged**
