### PR TITLE
Add conditional statement to check metricsKamon flag.

### PR DESCRIPTION
**Pull request by upgle**
Recently added all MetricEmitter logic does not check metricsKamon config is enabled.

```scala
if (TransactionId.metricsKamon) {
        MetricEmitter.emitHistogramMetric(token, tid.deltaToStart)
        MetricEmitter.emitCounterMetric(token)
}
```
https://github.com/apache/incubator-openwhisk/blob/925500cf8d34bb75bebd077ea057af236eba0b01/common/scala/src/main/scala/whisk/http/BasicHttpService.scala#L127

### CODE REVIEW

**Comment by rabbah** [comment]
@markusthoemmes this looks right to me - but please verify and merge.

**Comment by markusthoemmes** [comment]
@mhenke1 can you double-check please?

**Comment by markusthoemmes** [comment]
@upgle Is there a possibility to move this check inside the `MetricEmitter`? More importantly: What's the behavior of this if you don't have Kamon setup? Any error logs?

**Comment by upgle** [comment]
@markusthoemmes 
yes it is possible to move inside the MetricEmitter.

And Kamon always starts, regardless of `metrics_kamon: true` options (Kamon setup), it tries to send the meaningless metric without proper setting.
So it should be checked `TransactionId.metricsKamon` always.

Also, an error occurred in our custom kamon-backend metric system without setting like host, auth... (it is not statsd backend.)

**Comment by markusthoemmes** [comment]
PG5 112 🔵

**Pull request merged**
