### PR TITLE
refactoring loadbalacing service with an overflow queue

### PR DESCRIPTION
**Pull request by tysonnorris**
Unify overflow topic and revise invoker scheduling.
Includes:
- revert LoadBalancerData APIs to be synchronous (with updates pushed via replication)
- LoadBalancerService class replaced with LoadBalancerActorService (publish function sends a message)
- InvokerPool is configured outside of LoadBalancerServiceActor (and passed on construction; to make testing simpler)
- SpiLoader allows config injection (so that testkit ActorSystems can be injected with inline configs (instead of always reading application.conf)
- TestConnector enhanced to include a full TestMessagingProvider, to allow testing message flows

Note that one side affect is that a request arriving at controller0 that gets queued to overflow, MIGHT get routed to controller1 for invoker scheduling

This is supporting the "PR1" portion of https://cwiki.apache.org/confluence/display/OPENWHISK/Invoker+Activation+Queueing+Change

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Can we cut this into multiple commits or PRs even? Seems like

- Make LoadbalancerData synchronous
- LoadBalancerActorService

can be made 2 entirely separate, possibly subsequent PRs which will make this much much easier to review. WDYT?

**Comment by tysonnorris** [comment]
Sure, will create

- [ ] LoadBalancerData synchronous (see #2943)
- [ ] LoadBalancerActorService

Then overflow can be addressed after that

**Comment by markusthoemmes** [comment]
What's the status on this @tysonnorris? Did you have a chance to look at this in relation to the new sharding loadbalancer?

**Comment by markusthoemmes** [comment]
@tysonnorris any news?

**Comment by tysonnorris** [comment]
No news, too many other things in flight. Will get back to this at some point.

**Comment by markusthoemmes** [comment]
@tysonnorris I'll close this then for now. Please reopen a PR once this is being worked on again.

**Pull request closed without merging**
