### PR TITLE
Introduce separate Akka dispatchers for CouchDB and Kafka Clients (#2954)

### PR DESCRIPTION
**Pull request by bwmcadams**
- Rest of system continues to use the default system dispatcher

Refs #2954

## Description

This reopens the previous  #2956 PR; fork-join-executor wasn't the right choice previously and it is using Thread Pool dispatchers now, which are the correct way to handle this kind of IO separation with Akka. Defaults are set to what should be a reasonable starting point, especially given that couch and kafka now have their own separate execution pools from the "Default"/main system.

 Kafka and CouchDB clients each get their own dispatchers
  * This should prevent all of the akka based stuff from competing constantly for threads
  * Kafka and Couch can be tuned now based on individual needs
  * Using thread-pool dispatchers, which are best suited for these processes (default is fork-join)
- Dispatchers are defined in common `reference.conf`, so config can be overridden by dependents

Currently, OpenWhisk is sharing a single fork-join-executor across the board for the entire `ActorSystem`, which is less than ideal especially when dealing with potentially blocking IO. 

## Related issue and scope

- [x] I opened an issue to propose and discuss this change (#2954 )

## My changes affect the following components

- [ ] API
- [ ] Controller
- [x] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [x] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [x] Bug fix (generally a non-breaking change which closes an issue). (sort of a bug fix)
- [x] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes. (not easily testable in unit/integration)
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by rabbah** [comment]
@bwmcadams @chetanmeh this might be of use for other datastores so I wonder if we should rename the couch configuration to data store.

**Comment by chetanmeh** [comment]
> this might be of use for other datastores so I wonder if we should rename the couch configuration to data store.

+1

**Comment by bwmcadams** [comment]
Makes sense to me. I know it occurred to me while I was putting this
together, and tunable dispatchers for each component like this is a good
thing.

**Comment by chetanmeh** [comment]
@bwmcadams  #3779 introduces a new `S3AttachmentStore` where I was thinking to use the dedicated dispatcher. Do you plan to rename the dispatcher from `couch-dispatcher` to `db-dispatcher`?

**Comment by bwmcadams** [comment]
@chetanmeh good question. I think the quandary is whether there's a single shared `db-dispatcher` or a specific one per database implementation. My preference/instinct would be to have one per database implementation. The way a particular database driver is implemented can vary vastly from one to the other in terms of what the best dispatcher tuning is for it. Sharing a single dispatcher may not be ideal.

**Comment by chetanmeh** [comment]
@bwmcadams There are 2 aspects

1. Have a dedicated separate dispatcher for db operations
2. Dispatcher being tuned per DB driver implementation

Currently we have few storage impls which use Akka HTTP stack like CouchDB, S3 and ElasticSearch. So for them I think it would be better to have a generic `db-dispatcher` which is used by default. If any setup needs specific tuning then config can still be overridden for that deployment and later we can see if it makes sense to use a dedicated dispatcher for that kind of db.

So to start with lets have a generic `db-dispatcher` and later based on learning we can define specific one. This would allow us to at least meet 1 and still enabling option for 2.

Thoughts?

**Pull request merged**
