### PR TITLE
Reorganization of the "core" folder to move folders associated with runtimes to "actionRuntimes" in root folder

### PR DESCRIPTION
**Pull request by ServoKvd**

### CODE REVIEW

**Comment by rabbah** [comment]
did you forget to commit the action runtimes directory?

**Comment by ServoKvd** [comment]
Yes, looks like I did forget to commit the root folder in the last push.
I just pushed another pull-request  with just the updated root folder
Any idea how I can merge 2 pull requests into 1 - since the base did not change?

**Comment by ServoKvd** [comment]
Read few suggestions online for merging pull-requests -  looks a bit complex- and not recommended to merge pull requests. 
Can I have the following reviewed/merged first - Add actionRuntimes folder w/ Runtimes from core. 
- https://github.com/apache/incubator-openwhisk/pull/2933/commits/32b23c7111885b0901150505db394f2fa139a518
Then  review/merge the following:
https://github.com/apache/incubator-openwhisk/pull/2933/commits/c61b30e26ec75141e914bdcbf003e1d42a0d433b

**Comment by csantanapr** [comment]
I will run a PG

**Comment by csantanapr** [comment]
PG Playground2/2295/ looks good

**Pull request merged**
