### PR TITLE
Update JDK version to 8.131.11

### PR DESCRIPTION
**Pull request by cbickel**
FYI @sven-lange-last 
FYI @bjustin-ibm

### CODE REVIEW

**Comment by sven-lange-last** [comment]
Scala container was successfully built in Travis:

```
Step 12 : RUN curl --silent --location --retry 3 --cacert /etc/ssl/certs/GeoTrust_Global_CA.pem   --header "Cookie: oraclelicense=accept-securebackup-cookie;"   http://download.oracle.com/otn-pub/java/jdk/"${VERSION}"u"${UPDATE}"-b"${BUILD}"/d54c1d3a095b4ff2b6607d096fa80163/server-jre-"${VERSION}"u"${UPDATE}"-linux-x64.tar.gz   | tar xz -C /tmp &&   mkdir -p /usr/lib/jvm && mv /tmp/jdk1.${VERSION}.0_${UPDATE} "${JAVA_HOME}" &&   apt-get autoclean && apt-get --purge -y autoremove &&   rm -rf /tmp/* /var/tmp/*
 ---> Running in 65f8bc290ae0
Reading package lists...
Building dependency tree...
Reading state information...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
 ---> 02feda7e267f
Removing intermediate container 65f8bc290ae0
Step 13 : RUN update-alternatives --install "/usr/bin/java" "java" "${JRE_HOME}/bin/java" 1 &&   update-alternatives --install "/usr/bin/javac" "javac" "${JAVA_HOME}/bin/javac" 1 &&   update-alternatives --set java "${JRE_HOME}/bin/java" &&   update-alternatives --set javac "${JAVA_HOME}/bin/javac" &&   mkdir /logs
 ---> Running in 642647b74164
update-alternatives: using /usr/lib/jvm/java-8-oracle/jre/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-oracle/bin/javac to provide /usr/bin/javac (javac) in auto mode
 ---> 07c4f6f8b0e4
Removing intermediate container 642647b74164
Successfully built 07c4f6f8b0e4
Building 'scala' took 33.843 seconds
```

**Comment by cbickel** [comment]
PG3#649 is green.

**Comment by bjustin-ibm** [comment]
Thanks for taking the reins on this @cbickel

**Comment by ddragosd** [comment]
+0 - it's great we have fixed the problem. 
What do we do when this problem appears again in the future ? 

Any reason we can't use a base docker image for java from https://hub.docker.com/_/openjdk/ ? It would also speed up the build time. If needed we can open a separate issue to talk about this, but I thought I'd ask here first.

**Comment by sven-lange-last** [comment]
I have very limited knowledge about OpenJDK - but we definitely would have to test with regard to performance and robustness. In addition, the Oracle JDK brings tools like the flight recorder and VisualVM. GC will likely differ.

Any thoughts @rabbah ?

**Pull request merged**
