### PR TITLE
update to latest curator

### PR DESCRIPTION
**Pull request by tysonnorris**

### CODE REVIEW

**Comment by markusthoemmes** [comment]
@dgrove-oss I think you mentioned problems with curator 4.0?

**Comment by tysonnorris** [comment]
@dgrove-oss Thanks for mentioning this. I tried it and it indeed failed. 
Curator 4.0 has a compatibility mode for zk 3.4

I tried it successfully locally:
```[2017-12-05T22:47:32.722Z] [INFO] [??] [Invoker] invokerReg: creating zkClient to 192.168.99.101:2181
[2017-12-05T22:47:33.270Z] [INFO] Running in ZooKeeper 3.4.x compatibility mode
[2017-12-05T22:47:33.392Z] [INFO] Starting
[2017-12-05T22:47:33.429Z] [INFO] Client environment:zookeeper.version=3.4.11-37e277162d567b55a07d1755f0b31c32e93c01a0, built on 11/01/2017 18:06 GMT
[2017-12-05T22:47:33.450Z] [INFO] Client environment:host.name=invoker0
[2017-12-05T22:47:33.451Z] [INFO] Client environment:java.version=1.8.0_141
[2017-12-05T22:47:33.452Z] [INFO] Client environment:java.vendor=Oracle Corporation
[2017-12-05T22:47:33.453Z] [INFO] Client environment:java.home=/usr/lib/jvm/java-8-oracle/jre
[2017-12-05T22:47:33.460Z] [INFO] Client environment:java.class.path=/invoker/lib/akka-slf4j_2.11-2.5.6.jar:/invoker/lib/reactive-streams-1.0.1.jar:/invoker/lib/scala-parser-combinators_2.11-1.0.4.jar:/invoker/lib/zookeeper-3.4.11.jar:/invoker/lib/curator-client-4.0.0.jar:/invoker/lib/config-1.3.1.jar:/invoker/lib/scala.jar:/invoker/lib/kafka-clients-0.11.0.1.jar:/invoker/lib/scala-library-2.11.11.jar:/invoker/lib/akka-http_2.11-10.0.10.jar:/invoker/lib/akka-actor_2.11-2.5.6.jar:/invoker/lib/log4j-over-slf4j-1.7.25.jar:/invoker/lib/slf4j-api-1.7.25.jar:/invoker/lib/httpclient-4.4.1.jar:/invoker/lib/guava-20.0.jar:/invoker/lib/akka-stream_2.11-2.5.6.jar:/invoker/lib/HdrHistogram-2.1.9.jar:/invoker/lib/pureconfig_2.11-0.7.2.jar:/invoker/lib/akka-http-core_2.11-10.0.10.jar:/invoker/lib/jline-0.9.94.jar:/invoker/lib/logback-classic-1.2.3.jar:/invoker/lib/commons-codec-1.9.jar:/invoker/lib/macro-compat_2.11-1.1.1.jar:/invoker/lib/java-uuid-generator-3.1.3.jar:/invoker/lib/kamon-statsd_2.11-0.6.7.jar:/invoker/lib/jcl-over-slf4j-1.7.25.jar:/invoker/lib/netty-3.10.5.Final.jar:/invoker/lib/kamon-core_2.11-0.6.7.jar:/invoker/lib/slf4j-log4j12-1.6.1.jar:/invoker/lib/ssl-config-core_2.11-0.2.2.jar:/invoker/lib/audience-annotations-0.5.0.jar:/invoker/lib/invoker.jar:/invoker/lib/akka-stream-alpakka-file_2.11-0.14.jar:/invoker/lib/commons-collections-3.2.2.jar:/invoker/lib/snappy-java-1.1.2.6.jar:/invoker/lib/lz4-1.3.0.jar:/invoker/lib/jsr305-3.0.2.jar:/invoker/lib/akka-parsing_2.11-10.0.10.jar:/invoker/lib/caffeine-2.4.0.jar:/invoker/lib/logback-core-1.2.3.jar:/invoker/lib/akka-http-spray-json_2.11-10.0.10.jar:/invoker/lib/curator-framework-4.0.0.jar:/invoker/lib/shapeless_2.11-2.3.2.jar:/invoker/lib/junit-3.8.1.jar:/invoker/lib/scala-java8-compat_2.11-0.7.0.jar:/invoker/lib/curator-recipes-4.0.0.jar:/invoker/lib/spray-json_2.11-1.3.3.jar:/invoker/lib/log4j-1.2.16.jar:/invoker/lib/commons-io-2.4.jar:/invoker/lib/httpcore-4.4.1.jar
[2017-12-05T22:47:33.461Z] [INFO] Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
[2017-12-05T22:47:33.464Z] [INFO] Client environment:java.io.tmpdir=/tmp
[2017-12-05T22:47:33.465Z] [INFO] Client environment:java.compiler=<NA>
[2017-12-05T22:47:33.467Z] [INFO] Client environment:os.name=Linux
[2017-12-05T22:47:33.468Z] [INFO] Client environment:os.arch=amd64
[2017-12-05T22:47:33.468Z] [INFO] Client environment:os.version=4.4.100-boot2docker
[2017-12-05T22:47:33.469Z] [INFO] Client environment:user.name=root
[2017-12-05T22:47:33.469Z] [INFO] Client environment:user.home=/root
[2017-12-05T22:47:33.476Z] [INFO] Client environment:user.dir=/
[2017-12-05T22:47:33.478Z] [INFO] Initiating client connection, connectString=192.168.99.101:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@53f48368
[2017-12-05T22:47:33.570Z] [INFO] Opening socket connection to server 192.168.99.101/192.168.99.101:2181. Will not attempt to authenticate using SASL (unknown error)
[2017-12-05T22:47:33.597Z] [INFO] Default schema
[2017-12-05T22:47:33.609Z] [INFO] Socket connection established to 192.168.99.101/192.168.99.101:2181, initiating session
[2017-12-05T22:47:33.630Z] [INFO] Session establishment complete on server 192.168.99.101/192.168.99.101:2181, sessionid = 0x10001b186c60006, negotiated timeout = 40000
[2017-12-05T22:47:33.669Z] [INFO] State change: CONNECTED
[2017-12-05T22:47:33.675Z] [INFO] [??] [Invoker] invokerReg: connected to zookeeper
[2017-12-05T22:47:33.753Z] [INFO] [??] [Invoker] invokerReg: no prior assignment of id for invoker iname0
[2017-12-05T22:47:33.884Z] [INFO] [??] [Invoker] invokerReg: invoker iname0 was assigned invokerId 1```

**Comment by dgrove-oss** [comment]
thanks @tysonnorris.  I couldn't figure out the right gradle incantation when I tried it last time. LGTM

**Comment by tysonnorris** [comment]
@markusthoemmes can you provide some feedback here?

**Pull request merged**
