### PR TITLE
Update kubectl version in invoker Dockerfile

### PR DESCRIPTION
**Pull request by dgrove-oss**
Update version of kubectl executable in invoker Dockerfile
from 1.6.4 to 1.8.13 (most recent release in Kubernetes 1.8.x line).
Match minimum Kubernetes version of 1.8.x from openwhisk-deploy-kube.

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ x] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [ ] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [ ] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by dgrove-oss** [comment]
@bbrowning - see any problem with updating the kubectl version embedded in the invoker docker image?

Note, the `kubectl` executable in the invoker's docker image is only used with the `KubernetesContainerFactory`.

**Comment by dgrove-oss** [comment]
@bbrowning and @bwmcadams are you ok with the bump of kubectl in the invoker image to 1.8.x?  If so, could you merge this PR?

**Comment by sven-lange-last** [comment]
@dgrove-oss which Kube version are we targetting with the invoker image? IBM Cloud Kubernetes service is on Kube 1.10 at the moment...

**Comment by dgrove-oss** [comment]
the open deploy-kube project nominally supports Kube 1.8, 1.9, and 1.10.

The kubectl embedded in the invoker image is only used in a couple of code paths in the KubernetesContainerFactory.  We actually should get rid of it entirely, but it will take a little work in the KubernetesClient code used by the KubeContainerFactory.

**Comment by sven-lange-last** [comment]
Ok, thanks. So `kubectl` version 1.8 is a reasonable choice.

I'm also asking because `kubectl` 1.11 introduced an experimental `kubectl wait` command which is pretty helpful for scripting.

```
kubectl wait --help
Experimental: Wait for one condition on one or many resources

Options:
      --all-namespaces=false: If present, list the requested object(s) across all namespaces. Namespace in current
context is ignored even if specified with --namespace.
  -f, --filename=[]: identifying the resource.
      --for='': The condition to wait on: [delete|condition=condition-name].
  -o, --output='': Output format. One of:
json|yaml|wide|name|custom-columns=...|custom-columns-file=...|go-template=...|go-template-file=...|jsonpath=...|jsonpath-file=...
See custom columns [http://kubernetes.io/docs/user-guide/kubectl-overview/#custom-columns], golang template
[http://golang.org/pkg/text/template/#pkg-overview] and jsonpath template
[http://kubernetes.io/docs/user-guide/jsonpath].
  -R, --recursive=true: Process the directory used in -f, --filename recursively. Useful when you want to manage related
manifests organized within the same directory.
  -l, --selector='': Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2)
      --timeout=30s: The length of time to wait before giving up.  Zero means check once and don't wait, negative means
wait for a week.

Usage:
  kubectl wait resource.group/name [--for=delete|--for condition=available] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).
```

**Comment by bbrowning** [comment]
Bumping the Kube version makes sense to me. I'll let @bwmcadams do the review and merge dance.

Thanks!

**Comment by dgrove-oss** [comment]
It turned out to be pretty easy to implement the last couple of operations using the rest client, so we don't even need the kubectl exectuable in the invoker image anymore.  Closing this in favor of #3963

**Pull request closed without merging**
