### PR TITLE
akka thread pool tuning

### LINKED ISSUE #3226: akka thread pool tuning
two of akka's thread pools could use some tuning.

the first is the default pool used by our fork join scheduler. the akka fork join scheduler has a default setting of `throughput=5`, which means each thread/worker will process at most 5 events before yielding -- and thus risking a context switch.

the second is the io pool, which uses (by default) a pinned scheduler (i.e. threads pinned to processors); this pool handles incoming packets. it has a default size of 1, and its own default throughput of 5.

in the following experiments, i peg the pool size to 8, with a throughput of 200, and vary the throughput setting of the fork join scheduler. NOTE: the xput= rows in this table build on PR #3225 as their baseline. thus the xput=5 row is identical to the performance of PR #3225, as xput=5 is the default setting.

```
           p25   p50   p75    p90    p99     max
master     20ms  23ms  28ms   40ms   270ms  1.7s
xput=5     18ms  21ms  26ms   35ms   85ms   1.4s    (baseline #3225)
xput=200   20ms  23ms  28ms   39ms   74ms   407ms
xput=1000  18ms  21ms  25ms   33ms   64ms   277ms    <===
xput=2000  19ms  22ms  26ms   36ms  103ms   751ms
```

test protocol: wrk -t8 -c800 -d60s --latency
endpoint: blocking invokes of echo action
deployment: environments/local, local couchdb, 44-way with 48GB memory; 12 invokers
load driver: 16-way located in the same rack

### PR DESCRIPTION
**Pull request by starpit**
See the analysis in #3226 

Fixes #3226

PG2/2716

### CODE REVIEW

**Comment by markusthoemmes** [comment]
I couldn't verify any changes in the performance data in a distributed environment (16c/32g Controller and 20 4c/8g Invokers).

@bwmcadams Would give this a quick glance? I can't really determine the risk here.

**Comment by dubee** [comment]
@markusthoemmes, @bwmcadams, any updates on this one?

**Comment by bwmcadams** [comment]
@dubee the config changes themselves are fine, in context. I'll comment on the issue with questions/concerns.

**Comment by markusthoemmes** [comment]
@starpit given @bwmcadams's comments in the issue, how do you want to proceed with this PR?

**Comment by markusthoemmes** [comment]
Closing per @starpit's wish

**Pull request closed without merging**
