### PR TITLE
Restore Pretty Printing in Controller

### PR DESCRIPTION
**Pull request by dubeejw**
Relate to https://github.com/apache/incubator-openwhisk/issues/2635

### CODE REVIEW

**Comment by rabbah** [comment]
I was considering whether we wanted to restore his for the main API vs webactions. Which are more likely used with curl.

**Comment by dubeejw** [comment]
@rabbah, I'd rather keep the pervious behavior. Any suggestions on testing that doesn't require testing every single path?

**Comment by markusthoemmes** [comment]
Why would we need pretty printing either way? Isn't it more data in transport?

**Comment by rabbah** [comment]
For webactions I think it's a useful convenience because one tends to use curl often - at least I do and we use these examples in our docs. 

For the mainline API I think it's less important because i think generally one interacts with that via the cli which pretty prints.

**Comment by rabbah** [comment]
covered by https://github.com/apache/incubator-openwhisk/pull/2643.

**Pull request closed without merging**
