### PR TITLE
Create trigger activation only when active rule(s) are present

### PR DESCRIPTION
**Pull request by dubee**
## Description

When a trigger is invoked, an activation object is created even if active rules are not associated with the trigger. This activation entity is not used at all when active rules are not associated with the trigger though. These changes create the activation object only when active rules are present.

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [x] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by mdeuser** [comment]
is an activation record written to the db in this situation?  i was thinking that https://github.com/apache/incubator-openwhisk/pull/3262 did just that - not write out the activation record when the trigger had not active rules

**Comment by dubee** [comment]
@mdeuser, the activation is not written to the database, it is just needlessly created in the controller though and never used.

**Comment by dubee** [comment]
PG1 3618 🔵

**Comment by dubee** [comment]
TY @markusthoemmes!

**Pull request merged**
