### PR TITLE
use KeepAlive(false) (SocketOption) instead of Connection:close (HTTP header)

### PR DESCRIPTION
**Pull request by tysonnorris**
Some intermittent build failures in various runtimes that use `ActionContainer` for tests (which uses the akka http client as of recently) shows some errors where connections are prematurely terminated. 

## Description

In separate testing, I think this is related to use of `Connection: close` request header, to dissuade connection reuse.

This change:
* removes `Connection:close` header
* uses instead the `SO.KeepAlive(false)` (SocketOption); similar to the apache client setting to disable connection reuse

Since Akka client is not enabled by default in existing code except the `ActionContainer` test base class, this change and its affects are not obvious, until runtimes using this test class are running on this change. Locally testing, I was able to intermittently reproduce problems with the previous version, and have not seen problems with this new version.

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [x] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [x] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by markusthoemmes** [comment]
> Locally testing, I was able to intermittently reproduce problems with the previous version, and have not seen problems with this new version.

Can you specify what these problems were? The setting of the Apache client is not necessarily related to the underlying socket but rather instructs the connection pool not to reuse connections at all.

What you're disabling here is [TCP Keepalive probing](https://www.tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/#whatis) and not necessarily relevant to HTTP connection reuse at all.

**Comment by tysonnorris** [comment]
Here is an example of the problem https://github.com/apache/incubator-openwhisk/pull/2795#issuecomment-412958409

Previously, when using "Connection: close" header, akka client would periodically get these connection errors (but not always, and not with all client tests). I changed the keepalive setting based on the keepalive handling added to `ApacheBlockingContainerClient`, but I agree this impl is not related to HTTP connection pooling.

Some options I see are:
* determine a more appropriate way to disable connection reuse besides keepalive SocketOption (this was the only approach I found)
* determine why `Connection:close` causes intermittent failures with akka client (have had no luck there so far )
* don't use `PoolingRestClient` or `Connection: close` in `AkkaContainerClient`, rather force a new connection on each request using `Http().outgoingConnection(<container ip>)`; I'm not sure the real performance impact here, since [docs](https://doc.akka.io/docs/akka-http/current/client-side/connection-level.html) mention it is 'slow'
* use `PoolingRestClient`, but not `Connection:close`, and allow max connection reuse, but add `client.close()` as part of the `Container.pause()` workflow (to dispose connections when container is paused). Connection pool will be recreated on unpause.

**Comment by markusthoemmes** [comment]
The thing is: Does disabling TCP keepAlive also disable reuse of that connection since that's what we want to impact.

**Comment by tysonnorris** [comment]
@markusthoemmes given that I'm not sure how to verify this, what about the last approach I mentioned (and was there a reason to not do this when the other client was changed to not reuse connectioned?):

> use PoolingRestClient, but not Connection:close, and allow max connection reuse, but add client.close() as part of the Container.pause() workflow (to dispose connections when container is paused). Connection pool will be recreated on unpause.

**Pull request merged**
