### PR TITLE
Bumping Scala dependencies and clean up dependency usage.

### PR DESCRIPTION
**Pull request by markusthoemmes**
Lots of our dependencies are used transitively and are not explicitly declared. While it might work that way today, it can cause headaches with unexpected versions being used. This enables automatic checking of the declaration of all our dependencies and makes sure, the used dependencies are explicitly declared and no unused dependencies are declared at all.

- Bumps Scala to 2.11.11 (been there through transient dependencies anyway, this makes Eclipse happy again)
- Bump akka dependencies to the version our akka-http version was build with.
- Remove unused dependencies.

### CODE REVIEW

**Comment by rabbah** [comment]
@markusthoemmes I unassigned myself for now since we're not ready to merge this; reassign me when we're good to go.

**Comment by dubeejw** [comment]
@markusthoemmes, from the Travis log, looks like controller failed to start.

**Comment by dubeejw** [comment]
Restarted Travis, looks like controller failed to start on the previous run.

**Comment by rabbah** [comment]
@markusthoemmes labeling wip until we can sort out dependencies downstream.

**Comment by markusthoemmes** [comment]
Will close for now and reopen once appropriate.

**Pull request closed without merging**
