### PR TITLE
Fix misspelled words

### PR DESCRIPTION
**Pull request by nhat-nguyen**

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Thanks for the contribution. Got an Apache CLA on file?

**Comment by nhat-nguyen** [comment]
@markusthoemmes I don't. How should I do that? Google brought me up this: https://www.apache.org/licenses/icla.pdf

**Comment by markusthoemmes** [comment]
Yep, that sounds about right.

**Comment by nhat-nguyen** [comment]
I have signed the ICLA and sent it over to secretary@apache.org

**Pull request merged**
