### PR TITLE
Update Log Store Fetch

### PR DESCRIPTION
**Pull request by dubeejw**
Pass HTTP request and user `Identity` to log store's `fetchLogs()`

### CODE REVIEW

**Comment by dubeejw** [comment]
PG3 1906 ⏳

**Comment by rabbah** [comment]
Rather than pass http headers should we instead allow the identity type to be extensible with additional iam details?

**Comment by markusthoemmes** [comment]
I'd rather we pass in the entire `HttpRequest`. Query-string or body might be interesting to implementors as well?

@rabbah this is a lot about staging changes here and I think as an MVP it makes most sense to give `fetchLogs` access to the entire `HttpRequest`.

For anybody: The background of this is, that any backend Logstore might be subject to a different authentication than OpenWhisk itself. Rather than entangle everything and anything in OpenWhisk authentication means it might be beneficial to provide a "custom" API.

Thinking about it, just the headers might be fine as a first step.

**Comment by dubeejw** [comment]
@markusthoemmes, added a second commit that send the HTTP request to the log store instead of just the HTTP headers.

**Comment by dubeejw** [comment]
PG3 1908 🔵

**Pull request merged**
