### PR TITLE
#3401: Moved local variables to Constants and renamed all occurences

### PR DESCRIPTION
**Pull request by kiran002**
## Description

Consolidated and moved all the annotations into a single location as described in the issue (#3401) and replaced all occurences.

## Related issue and scope

- [x] I opened an issue to propose and discuss this change (#????)
https://github.com/apache/incubator-openwhisk/issues/3401
## My changes affect the following components

- [ ] API
- [x] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [x] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [x] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [ ] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [x] I updated the documentation where necessary.

### CODE REVIEW

**Comment by kiran002** [comment]
@rabbah Thanks for the quick review! I am running scalafmt gradle task, but its not doing anything. I tried setting up Scalariform (https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md#coding-standards), but it still does not format the code like it is in the master branch. Do you know what the problem could be? BTW, I am using IntelliJ

**Comment by rabbah** [comment]
```
/home/travis/build/apache/incubator-openwhisk/tests/src/test/scala/system/basic/WskActionTests.scala:27: Unused import
import org.apache.openwhisk.core.entity.{Annotations, WhiskAction}
                                                      ^
/home/travis/build/apache/incubator-openwhisk/tests/src/test/scala/system/basic/WskConsoleTests.scala:35: Unused import
import org.apache.openwhisk.core.entity.{Annotations, WhiskAction}
                                                      ^
/home/travis/build/apache/incubator-openwhisk/tests/src/test/scala/system/basic/WskRestBasicTests.scala:36: Unused import
import org.apache.openwhisk.core.entity.{Annotations, WhiskAction}
```

**Comment by rabbah** [comment]
@kiran002 sorry you're having trouble with the formatting. This is how I do it from the command line: `./gradlew scalafmtAll` at the root of the project.

**Comment by kiran002** [comment]
@rabbah thanks for helping out, i have been trying to run that task and nothing happens,

```
~/myrepo/incubator-openwhisk$ ./gradlew scalafmtAll

BUILD SUCCESSFUL in 2m 9s
25 actionable tasks: 25 executed
```

**Comment by chetanmeh** [comment]
Scala formatter uses the `.scalafmt` file in root folder for config. In Intellij I have to set Editor -> Code Style -> Scala -> Formatter to `scalafmt` and `Reformat on file save`. 

> ./gradlew scalafmtAll

Given that debug log says its actually reformatting then may be the files need to be re-added to git changelist and then committed?

**Comment by kiran002** [comment]
@chetanmeh thanks a lot for your reply, i am doing essentially doing what you have outlined and there are no difference being generated. When i make some incorrect indentations and run `./gradlew scalafmtAll`, I can see that the formatting is indeed fine.

Does Travis really fail because of the formatting? because I can see in the logs, all the checks passed only file upload failed.

**Comment by chetanmeh** [comment]
My response was more related to sclafmt discussion ... did not realized that you were trying to figure out the build failure root cause. For this PR the build is failing due to a [test][1] which fails intermittently and not related to your changes.

I have restarted the build. If you see failure unrelated to your change then try closing and reopening the PR as that would cause travis to retrigger the build

[1]: https://scans.gradle.com/s/vi47kj5lb5rno/tests/failed

**Comment by rabbah** [comment]
Thanks @kiran002 for the contribution.

**Pull request merged**
