### PR TITLE
Support client certificate on cli and nginx

### PR DESCRIPTION
**Pull request by ningyougang**
In order to increase the security of auth, it is necessary to add client
certificate on cli and nginx. So user can use wsk -i property set --cert
openwhisk-client-cert.pem --key openwhisk-client-key.pem to pass client
certificate to nginx.

### CODE REVIEW

**Comment by style95** [comment]
LGTM.
If you are trying to open a pr in upstraem and get feedbacks, it would be great to specify that this is the first pr of two subsequent prs(server side).

But I am anxious that they will not accept it without server side changes.

**Comment by ningyougang** [comment]
The whole logic is that if add client certificate, there has two authenticate method
* When use `wsk -i property --cert cert.pem --key key.pem............`, the controller will ignore `--auth` verfiy, directly passed.
* keep original logic for authenticate, if execute like this `wsk -i property --auth ${auth}.....`

**Comment by style95** [comment]
But to pass authentication, we need changes in controller, right?

**Comment by ningyougang** [comment]
yes, in order to keep the whole logic (already said above), should make changes in controller,
if controller identities nginx has verified the client certificate, the controller has no need to verify auth key.

**Comment by ningyougang** [comment]
see here:https://github.com/apache/incubator-openwhisk/pull/2427

**Pull request closed without merging**
