### PR TITLE
Update akka to 2.5.12 and akka-http to 10.1.1.

### PR DESCRIPTION
**Pull request by markusthoemmes**
## Description
The newest akka-http contains a new connection-pool implementation which we can make use of to stabilize our akka-http based clients (most notably couchdb).

## My changes affect the following components

- [ ] API
- [X] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [X] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [X] Data stores (e.g., CouchDB)
- [X] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [X] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [X] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [X] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
~~- [ ] I added tests to cover my changes.~~
~~- [ ] My changes require further changes to the documentation.~~
~~- [ ] I updated the documentation where necessary.~~

### CODE REVIEW

**Comment by mdeuser** [comment]
if this upgrade involves more than a couple steps, maybe create an operations doc outlining the steps and caveats for future akka upgrades

**Comment by markusthoemmes** [comment]
@dubee Happy to do that (you can also revive your PR if you want to). Felt like it's easier to do it without the variable (read: less parts involved) in terms of getting other repos to compile as well.

But sure, let's try.

**Comment by dubee** [comment]
PG3 2143 ⏳

**Comment by markusthoemmes** [comment]
@dubee PG1 2794 👍

**Pull request merged**
