### PR TITLE
Run scancode utility from the utility repo/project

### PR DESCRIPTION
**Pull request by mrutkows**
In an effort to share scancode(and other utils) across project repos., (and not pre-req the entire openewhisk repo. for travis/builds) we have it now in a new "utility" repo. (incubator-openwhisk-utilities) and will clone/invoke it (and potential future utils) from there.

### CODE REVIEW

**Comment by rabbah** [comment]
Will also need to update the wiki (pre commit hook tip): https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines

**Comment by mrutkows** [comment]
@rabbah thanks for the reminder.

**Comment by mrutkows** [comment]
@rabbah updated https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines Please let me know what you think...

**Comment by rabbah** [comment]
Thanks - I followed the instructions and ran scancode from the new util repo. I modified my pre-commit hook accordingly:

```
#!/usr/bin/env bash
python /my/path/to//incubator-openwhisk-utilities/scancode/scanCode.py .
```

I may edit the page to add the pre-hook suggestion back.

**Comment by mrutkows** [comment]
@csantanapr any comments?

**Comment by csantanapr** [comment]
I don't see the hook information in the wiki

**Comment by rabbah** [comment]
I know several people deploy the hook - perhaps a note to the dev list to warn them the hook is about to break?

**Comment by rabbah** [comment]
I updated the page to include the pre-commit hook instructions again.

**Comment by csantanapr** [comment]
Also there are other repos that in in their Travis integration will brake because of the removal.
- catalog
- package-kafka
- package-alarms
- package-cloudant
- cli
- client-go

@mrutkows Why we don't do it in two phases?

1. Update all repos for their travis to use the new incubator-openwhisk-utilities repo
Announce in the dev list and slack that if you have a hook or using scancode from the main repo, you have a week to update to use incubator-openwhisk-utilities
2. After a week remove scancode from main repo.

**Comment by csantanapr** [comment]
@rabbah 
I was about to add the hook to wiki and then saw it already there
>I updated the page to include the pre-commit hook instructions again.

**Comment by mrutkows** [comment]
@csantanapr did not see your comment after previous review... updating other repos. now...
https://github.com/apache/incubator-openwhisk-catalog/pull/225

others in-progress ASAP

**Comment by csantanapr** [comment]
@mrutkows This PR broke a bunch of integrations. This the reason I didn't approved this PR

**Comment by mrutkows** [comment]
@csantanapr did not see a red x for changes post rr review

**Pull request merged**
