### PR TITLE
Remove deadcode and clone/own.

### PR DESCRIPTION
**Pull request by rabbah**
Removing what appears to be unnecessary/dead code.
Also removed some code duplication around resolving fully qualified names.

## My changes affect the following components

- [x] Tests

## Types of changes

- [x] Enhancement or new feature (adds new functionality).

### CODE REVIEW

**Comment by dubee** [comment]
PG2 2952 🐎

**Comment by dubee** [comment]
@rabbah, can you rebase having trouble with a PG.

**Comment by rabbah** [comment]
done - thanks for the pg.

**Comment by dubee** [comment]
PG4 1515 ☃️

**Comment by dubee** [comment]
PG4 1515 🔵

**Pull request merged**
