### PR TITLE
Remove API for listing all entities in namespace

### PR DESCRIPTION
**Pull request by rabbah**
Proposed patch for https://github.com/apache/incubator-openwhisk/issues/3153.

### CODE REVIEW

**Comment by rabbah** [comment]
@csantanapr The node runtimes have been updated, and the CLI as well. I think this is ready then.

**Comment by rabbah** [comment]
pg5/104 🏃

**Comment by cbickel** [comment]
In general this PR looks good to me.
But this will be a breaking change in our api, right?
Does this has to be communicated to the community and customers of all the OpenWhisk-installations before we merge it?
And what about the cli command `wsk list`? Will the CLI make 4 requests instead?

**Comment by rabbah** [comment]
@cbickel https://lists.apache.org/thread.html/d49727a3057759bd2879b5b4e37a63e3b6d9b916143f9d315e20d2dc@%3Cdev.openwhisk.apache.org%3E

also I've already updated the CLI and npm openwhisk to sugar the call (and make 4 calls instead).

**Comment by mrutkows** [comment]
See PR: https://github.com/apache/incubator-openwhisk-cli/pull/191
"Handle namespace API listing on the client. #191"

**Comment by csantanapr** [comment]
@cbickel OK to merge this?

**Comment by cbickel** [comment]
@csantanapr As you are the only Assignee and not one of the Reviewers, you can decide.

**Pull request merged**
