### PR TITLE
Support SPI for ContainerPool and ContainerProxy

### LINKED ISSUE #3662: SPI for ContainerProxy and ContainerPool
As of now, SPI concept is applied in many parts of OpenWhisk.
If same concept is applied to `ContainerProxy` and `ContainerPool`, it would give users more options and make OW more flexible.

### PR DESCRIPTION
**Pull request by style95**
This closes #3662.

## Description
It will apply SPI to `ContainerPool` and `ContainerProxy`.
Current `ContainerPool` and `ContainerProxy` are renamed with `Default` prefix.

## Related issue and scope

- [x] I opened an issue to propose and discuss this change (#3662)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [x] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [x] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by style95** [comment]
Could anyone trigger the build again please?
It seems failing test is not related to my changes.

**Comment by csantanapr** [comment]
@style95 
Closing the PR and then re-opening the PR will trigger the build again in Travis

**Comment by style95** [comment]
@csantanpr thank you for the good tip.

**Comment by style95** [comment]
@tysonnorris suggested to use a single SPI implementation for `ContainerProxy` and `ContainerPool`.

At first time, I thought of this kind of approach.

```scala
trait ContainerPoolProvider extends Spi {
  def getContainerPoolProps(childFactory: ActorRefFactory => ActorRef,
            poolConfig: ContainerPoolConfig,
            activationFeed: ActorRef,
            someConfig: Option[PrewarmingConfig] = None): Props

  def getContainerProxyProps(factory: (TransactionId, String, ImageName, Boolean, ByteSize, Int) => Future[Container],
            ack: (TransactionId, WhiskActivation, Boolean, InstanceId, UUID) => Future[Any],
            store: (TransactionId, WhiskActivation) => Future[Any],
            collectLogs: (TransactionId, Identity, WhiskActivation, Container, ExecutableWhiskAction) => Future[ActivationLogs],
            instance: InstanceId,
            poolConfig: ContainerPoolConfig,
            unusedTimeout: FiniteDuration = timeouts.idleContainer,
            pauseGrace: FiniteDuration = timeouts.pauseGrace): Props

  def requiredProperties: Map[String, String]
}
```
So we can create both `ContainerProxy` and `ContainerPool` implementation with one trait.
But with this approach, companion object of them should mix in the same trait, `ContainerPoolProvider`.
Since that trait has two abstract methods, it is required for all objects which mix in this trait to override both methods.
Accordingly `ContainerProxy` and `ContainerPool` should override unnecessary methods respectively.

One option is to make `ContainerProxy` as a inner class of `ContainerPool` and only expose `ContainerPool` via SPI.
But it might introduce huge changes.

As of now I am not quite sure which one is right direction.
I am holding to have multiple SPI for them in one hand, and to make `ContainerProxy` as an inner class of `ContainerPool` in the other hand.

WDYT?

**Comment by rabbah** [comment]
Discalimer: i need to catch up on the tech exchange and various other write ups. But at first glance two adapters avoids conflating separate concerns. I do not see why they should be mixed or nested.

**Comment by style95** [comment]
The basic idea behind above approach is, `ContainerProxy` and `ContainerPool` have strong correlation to each other.
I am not sure we can independently use `ContainerProxy` or `ContainerPool`.
Logics in `ContainerProxy` do affect the scheduling and pool managing logics in `ContainerPool`.
So I thought if we make `ContainerProxy` as an inner class of `ContainerPool` then we can have better cohesion.

**Comment by markusthoemmes** [comment]
@style95 this has rotted quite a bit and the dev-list discussions seem to move in another direction. I'll close this for now due to inactivity. Please feel free to reopen it if a proposal going this way is discussed and agreed upon on the dev-list.

Thanks a lot for your work so far, very appreciated! 🎉

**Comment by style95** [comment]
@markusthoemmes got it.
Thanks.

**Pull request closed without merging**
