### PR TITLE
Use Gauge metric instead of Histogram where applicable

### PR DESCRIPTION
**Pull request by chetanmeh**
This PR introduces an abstraction for [Kamon Gauge](https://kamon.io/docs/latest/core/metrics/#gauges)

## Description
As mentioned in #4311 at some places we are using Histogram to track metric which should instead be tracked as Gauge. This PR converts such usage to Gauge based

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#4311)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [ ] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [ ] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by chetanmeh** [comment]
Note that with this change some of the metrics which were earlier tracked as histogram are now converted to Gauge. So its sort of breaking change. However I am not sure how much usable was previous Hostogram based tracking so may be fine to do such a change

@SugandhaAgrawal @vvraskin @sven-lange-last Please have a look and review!

**Comment by rabbah** [comment]
Thanks @SugandhaAgrawal for taking a look.

**Comment by SugandhaAgrawal** [comment]
@chetanmeh I am currently testing the changes from your PR in Grafana - Just FYI

**Comment by SugandhaAgrawal** [comment]
@chetanmeh 👍 This looks good. Feel free to merge. Thanks again for doing this

**Pull request merged**
