### PR TITLE
Replace List() occurrences with List.empty

### PR DESCRIPTION
**Pull request by dubee**
## Description

Use List.empty, which is provided by a persistent singleton object, instead of creating new case classes by using List().

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [ ] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [ ] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by chetanmeh** [comment]
Given that this is a recurring work #3359 should we look into configuring a code style check plugin. For example [scapegoat][1] has a `PreferSeqEmpty` check which can flag such usage. 

Only issue is I [do not find a Gradle plugin](sksamuel/scapegoat#195) for it. But looking at [sbt plugin][2] it should be possible to add it directly via some scripting in our case

[1]: https://github.com/sksamuel/scapegoat
[2]: https://github.com/sksamuel/sbt-scapegoat/blob/master/src/main/scala/com/sksamuel/scapegoat/sbt/ScapegoatSbtPlugin.scala

**Comment by rabbah** [comment]
good idea @chetanmeh +1

**Comment by rabbah** [comment]
@dubee can we combine all the prs into one?

**Comment by chetanmeh** [comment]
Opened #3931 to track configuring a code analysis plugin

**Pull request closed without merging**
