### PR TITLE
remove hardcode prewarm nodejs:6 allow nodejs:default

### PR DESCRIPTION
**Pull request by csantanapr**

### CODE REVIEW

**Comment by csantanapr** [comment]
currently working on `nodejs:8` this allow me to select which is prewarm based on ansible setting.

**Comment by rabbah** [comment]
The indirection is dangerous here since you can end up affecting the setting for a majority of actions unintentially. Did you consider factoring out the prewarm kind(s) to ansible instead?

**Comment by csantanapr** [comment]
@rabbah yes I considered moving to ansible.
Was thinking maybe an explicit kind selection, and not assume default for example a top level runtimeManifest property:
```yaml
runtimesManifest:
  prewarmKind:"nodejs:6"
```

what you think?

**Comment by rabbah** [comment]
Instead of a new top level property you could add a property prewarm as part of the kind declaration. There is a nuance you also need to potentially declare the memory bound as well.

**Comment by csantanapr** [comment]
Oh I forgot to reply.

Yes I agree, re defining the stem cell kind in configuring in runtimeManiFest JSON property, or another property, then can driven thru ansible or any config.

In terms of getting it done, 
not high priority, I thought I was going to be able to deploy in travis for the runtimes (i.e. swift, java) and not required nodejs runtime, but then I figured that the health protocol between controller and invoker requires a echo/hello action in nodejs.

I'm happy if you want to give it a stab @rabbah

**Pull request closed without merging**
