### PR TITLE
Ignore IntelliJ '.iml' project file

### PR DESCRIPTION
**Pull request by qabbasi**

### CODE REVIEW

**Comment by rabbah** [comment]
Thanks for the patch. Do you have an Apache CLA on file?

**Comment by qabbasi** [comment]
Obviously my first commit to an Apache project :) I just submitted my signed ACL to Apache...

**Comment by rabbah** [comment]
Thanks for the first contribution!

**Comment by csantanapr** [comment]
thanks for the contrib 🌮

**Pull request merged**
