### PR TITLE
bump kafka broker version to 0.11.0.1

### PR DESCRIPTION
**Pull request by dgrove-oss**

### CODE REVIEW

**Comment by dgrove-oss** [comment]
ches/kafka doesn't provide 0.11.  need to pick a different dockerhub repo and it isn't obvious to me which one to pick, so closing for now.

**Comment by csantanapr** [comment]
@dgrove-oss try this one https://hub.docker.com/r/wurstmeister/kafka/
I see 0.11 and also 1.0

**Comment by chetanmeh** [comment]
wurstmeister repo is also being used in devtools docker-compose https://github.com/apache/incubator-openwhisk-devtools/blob/master/docker-compose/docker-compose.yml#L19

**Comment by dgrove-oss** [comment]
Thanks for the pointer, I'll give it a whirl

**Comment by dgrove-oss** [comment]
PG2 2358 - queued

**Comment by dgrove-oss** [comment]
Redundant with #2744.  Closing.

**Pull request closed without merging**
