### PR TITLE
Move routemgmt install files to incubator-openwhisk-cli; Modify  ansible scripts accordingly

### PR DESCRIPTION
**Pull request by ServoKvd**

### CODE REVIEW

**Comment by ServoKvd** [comment]
Dependency on https://github.com/apache/incubator-openwhisk-apigateway/pull/265/commits/45c8f124580bafee965128581557b17dc7645a92
Build will fail, without the changes in incubator-openwhisk-apigateway

**Comment by csantanapr** [comment]
There is has being changes to apigw files, and there are conflicts now

**Comment by rabbah** [comment]
@csantanapr do we still want to do this?

**Comment by rabbah** [comment]
Closing for now.

**Pull request closed without merging**
