### PR TITLE
Add maven plugin to build.grade

### PR DESCRIPTION
**Pull request by chetanmeh**
- Adds `maven` plugin to build.gradle files for common, controller and
invoker.
- Enables support for generating source jars
- Uses `org.apache.openwhisk` as groupId
- Uses `0.0.1-SNAPSHOT` as current version

PR for #3060

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Awesome, thanks for taking this on! 🎉 

Any chance to do the same to our tests, so the external repos can rely on the published jar rather than the whole repository here?

**Comment by chetanmeh** [comment]
> Any chance to do the same to our tests, so the external repos can rely on the published jar rather than the whole repository here?

Missed including that. Updated the PR to also publish jars for "tests" module. Its sources are published with classifier `test-sources`

**Comment by csantanapr** [comment]
I was thinking using Jenkins build script that today pushes images on every master build already.

**Comment by csantanapr** [comment]
Asked @chetanmeh to update the jenkinsfile with this PR or seperate PR

**Comment by chetanmeh** [comment]
> Adding documentation on how to use these tasks would be very valuable so we can use it in the future to actually publish stuff. (+ I can verify locally that it works as the tasks are unused for now)

@markusthoemmes  The doc discussion was more for #3059. To try the change locally you just need to run. Later once its integrated with jenkins end users would typically not need to do it locally. So not sure if we need to document this in docs

    ./gradlew :core:controller:install

And then you can see controller artifacts at ~/.m2/repository/org/apache/openwhisk/controller

> Asked @chetanmeh to update the jenkinsfile with this PR or seperate PR

@csantanapr Sure would do this in a separate PR

**Comment by chetanmeh** [comment]
Few references for changes in main build.gradle

The use of maven plugin somehow also enables the zipDist and hence gradle starts creating and publishing the distribution in zip format also in addition to tar. So to disable that 2 steps are required

```
  //Avoid generating the zip files from maven installations
            distZip {
                enabled false
            }

            configurations.archives.with {
                artifacts.remove artifacts.find { it.archiveTask.is distZip }
            }
```

First part disables distZip but then it cause issue in install. So zip artifact needs to be explicitly removed. See discussion [here][1]

[1]: https://discuss.gradle.org/t/how-to-exclude-zip-only-from-archives-for-maven-repo-upload/13354/2

**Comment by chetanmeh** [comment]
Also opened #3082 to ensure that addition of new maven artifacts do not increase the build context for creating docker images

**Comment by chetanmeh** [comment]
@markusthoemmes  Anything more to be done related to this PR before it can be merged?

**Comment by chetanmeh** [comment]
@markusthoemmes  I have rebased the PR to current master. Can this PR be merged now?

**Comment by markusthoemmes** [comment]
@csantanapr A quick glance from your release-experienced view please?

**Comment by chetanmeh** [comment]
@csantanapr Can you have a look here so that this PR can be merged?

**Comment by chetanmeh** [comment]
Note that for common/scala module the jar name is `scala-0.0.1-SNAPSHOT.jar`. Below is how this is referred in a different module

```
dependencies {
    compile "org.apache.openwhisk:scala:0.0.1-SNAPSHOT"
}
```
This is because of module dir name being `scala`. Should be change it to common-xxx.jar or something else?

**Comment by csantanapr** [comment]
>This is because of module dir name being scala. Should be change it to common-xxx.jar or something else?

Yeah I think it would be better to call it `common`

**Comment by chetanmeh** [comment]
After discussing with @csantanapr  modified the build to produce jars following pattern "openwhisk-<module>-xxx.jar". So with this change we produce following artifacts

1. commons/scala 
    - openwhisk-common-\<version\>.jar
    - openwhisk-common-\<version\>-sources.jar
    - openwhisk-common-\<version\>-tests.jar
    - openwhisk-common-\<version\>-test-sources.jar
2. core/invoker
    - openwhisk-invoker-\<version\>.jar
    - openwhisk-invoker-\<version\>-sources.jar
    - openwhisk-invoker-\<version\>-tests.jar
    - openwhisk-invoker-\<version\>-test-sources.jar 
3. core/controller 
    - openwhisk-controller-\<version\>.jar
    - openwhisk-controller-\<version\>-sources.jar
    - openwhisk-controller-\<version\>-tests.jar
    - openwhisk-controller-\<version\>-test-sources.jar 
4. tests 
    - openwhisk-tests-\<version\>.jar
    - openwhisk-tests-\<version\>-sources.jar
    - openwhisk-tests-\<version\>-tests.jar
    - openwhisk-tests-\<version\>-test-sources.jar 

With this running `gradlew install` would install these jars to _~/.m2/repository/org/apache/openwhisk_ folder

Note that this currently does not add support for deploy and publishing. That would need to be done in a separate PR. It would only install the artifacts in local maven repo

**Comment by csantanapr** [comment]
Playground4/1287 🔵

**Pull request merged**
