### PR TITLE
Make OpenWhisk CLI available only via redirect

### PR DESCRIPTION
**Pull request by dgrove-oss**
As was already done with the iOS starter app and the blackbox SDK,
switch to making the cli binaries available via a redirect to the
openwhisk-cli release page instead of copying cli binaries into
the edge container.  As discussed in issue #2152 this eliminates
the need for a custom OpenWhisk edge image for downstream deployments.

Also update GoCLINginxTests to check for redirects instead of direct
downloads and remove the cli role and related variable definitions
from ansible.

### CODE REVIEW

**Comment by dgrove-oss** [comment]
Closes #2152

**Comment by dgrove-oss** [comment]
Overly aggressive; I need to bring back support for downloading the cli to $OPENWHISK_HOME/bin.

**Comment by dgrove-oss** [comment]
needs labels: review, companion.

PG1 2449 🏃

**Comment by csantanapr** [comment]
@dgrove-oss This is not quite what we agreed.
I don't think we should remove all options, In my comment https://github.com/apache/incubator-openwhisk/issues/2152#issuecomment-350508205

I said that is OK to add a 3rd option `remote_redirect`, leaving the other 2 options in place.
We can update doc to mention that `local` and `remote` are deprecated, and eventually going to be removed.

Also that for kube deployment only the `remote_redirect` is the way the nginx is configured.

**Comment by dgrove-oss** [comment]
will redo; easier to start over on new branch. closing.

**Pull request closed without merging**
