### PR TITLE
Move docker runtime into it's own repo 

### PR DESCRIPTION
**Pull request by csantanapr**
Related to #2791 

Repo located here now: https://github.com/apache/incubator-openwhisk-runtime-docker

Depends on merging first python and swift PRs
- #2822 Move swift runtime into it's own repo 
- #2843 Move python runtime into it's own repo

### CODE REVIEW

**Comment by csantanapr** [comment]
Do not merge this yet.

**Comment by csantanapr** [comment]
This is ready now, but after merging #2822 and #2843 
🔵 PG 2 2163

**Comment by rabbah** [comment]
can you rebase this?

**Comment by csantanapr** [comment]
Rebasing as these two are merged now:
#2822 Move swift runtime into it's own repo
#2843 Move python runtime into it's own repo

**Comment by csantanapr** [comment]
@rabbah using 301 based on feedback take a look 90106a9571d25e28e0c6973949ea29d89f468b85

**Comment by csantanapr** [comment]
PG good 🚀 Playground4 898

**Pull request merged**
