### PR TITLE
Add retry to rate-throttle tests becasue of the possiblility, that it…

### PR DESCRIPTION
**Pull request by cbickel**
… gets refreshed during the test

In our pipeline, it happened, that the test `respect overridden rate-throttles of  1` failed, with the error `exit code: 0 was not equal to 173`.

The test started at 12:41:58.414 and was finished at 12:42:01.056.

So it failed, because the amount of invoked actions in the current minute has been reseted in the controller between the two calls.

PG4#670 started.

### CODE REVIEW

**Comment by rabbah** [comment]
Is there a way we could attempt to settle the throttle instead?  

Hmm maybe if we provide the quota in the response in general it's useful and then the tests can deal with that accordingly.

**Comment by rabbah** [comment]
Ah I misunderstood - so this is a case where we expected the request to be throttled and it wasn't. The calculation in the test setup then is wrong, it should compensate for this... iirc that was the intention.

**Comment by markusthoemmes** [comment]
@rabbah these are the new tests I added for namespace specific throttles. They don't contain the settle/retry logic of the other ones.

**Comment by markusthoemmes** [comment]
@cbickel the test is still race prone though because you can have overlapping fires where it'd still fail because the first one would get throttled then. Maybe we should fire twice regardless of return code and verify that at least one of them got the expected return code to guard against that?

**Pull request merged**
