### PR TITLE
Remove the dependencies when running tests

### PR DESCRIPTION
**Pull request by houshengbo**
Closes: #3178

### CODE REVIEW

**Comment by jonpspri** [comment]
Ooo!  I vote yes, because this was also mucking up the CLI tests.

**Comment by rabbah** [comment]
We’re making harder and harder to develop across the entire stack. These dependencies made sure the container images were fresh before running the container unit tests. Rather than remove we should provide ways to bypass.

**Comment by jonpspri** [comment]
Well, to make it all work in what I'm doing with 'incubator-openwhisk-cli', I had to add this stanza to 'settings.gradle'.  Maybe we should make this available in 'incubator-openwhisk' as a file to `apply`?  I'm on sleep deprivation, so there could be many reasons that NOT a good idea...

```
def owPath = System.getenv("OPENWHISK_HOME") ?: '../incubator-openwhisk'
def owDirectory = new File(owPath)

if (!owDirectory.exists()) {
    throw new GradleScriptException(
        "Environment variable OPENWHISK_HOME must point to a valid OpenWhisk build", null)
}

include 'clitests'; project(':clitests').projectDir = new File(owDirectory, 'tests')

[   'common:scala',
    'core:controller',
    'core:invoker',
    'actionRuntimes:nodejs6Action',
    'actionRuntimes:actionProxy',
    'actionRuntimes:pythonAction',
    'actionRuntimes:python2Action',
    'actionRuntimes:javaAction',
    'actionRuntimes:swift3.1.1Action',
    'sdk:docker',
    'tests:dat:blackbox:badaction',
    'tests:dat:blackbox:badproxy'
].each() { p ->
    include p
    project(':'+p).projectDir = new File(owDirectory, p.replaceAll(':','/'))
}

include 'tests'
```

**Comment by csantanapr** [comment]
I'm OK removing since settings.gradle cover this projects, and when user builds which is before running any tests, he will build with `./gradlew distDocker` and the images will be there to be use by the tests.

**Comment by markusthoemmes** [comment]
The tests rely on those images so the tests should have a dependency on them, no?

You can always create a specific test-target which excludes those dependencies, which I'd prefer here.

**Comment by csantanapr** [comment]
That’s also good to create a new target for environments were a specific image tag want to be use and avoid the rebuild and trashed on what’s already prepared. Like a lean target that skips this dependencies assuming that deos are already taken care. 

The use case is for the CI/CD of Apache release automation where a specific tag of the runtimes would be use and build before running the tests.

**Comment by markusthoemmes** [comment]
@houshengbo comments on my concerns above?

**Comment by markusthoemmes** [comment]
Closing as abandonend. Please ping me to reopen if you want.

**Pull request closed without merging**
