### PR TITLE
Set user agent header in API GW requests

### PR DESCRIPTION
**Pull request by mdeuser**
- Set the User-Agent header to "OpenWhisk CLI" to better indicate the client context to the API GW
- jshint fixes

### CODE REVIEW

**Comment by mdeuser** [comment]
pg3/806

**Comment by mdeuser** [comment]
@csantanapr - for your review.  earlier pg4/453 had unrelated failures; rerunning pg3 now

**Comment by csantanapr** [comment]
To capture some of the offline discussion with @mdeuser 

User Agents value needs to follow spec
https://tools.ietf.org/html/rfc2616#section-3.8

```
  product         = token ["/" product-version]
       product-version = token

   Examples:

       User-Agent: CERN-LineMode/2.15 libwww/2.17b3
       Server: Apache/0.8.4
```
One idea is to have something like this that identifies that the request is coming from the web action, also passing some type of product-version
```
"User Agent": "OpenWhisk-Routemgt/4567"
```
```
WSK_BUILD_NUMBER = wsk property get | grep "API build number"
```
```
wsk package update routemgt --param __ow_version $WSK_BUILD_NUMBER
```

**Comment by mdeuser** [comment]
The web action could also append any incoming Agent-Header value to the final Agent-Header sent to the API GW

**Comment by rabbah** [comment]
This needs rebasing to resolve conflicts. Is this otherwise done?

**Comment by mdeuser** [comment]
@rabbah - A bit more work is needed to complete this item; other issues took priority; but, this is still on the radar.

**Comment by mdeuser** [comment]
pg2/1901

**Pull request merged**
