### PR TITLE
[WIP] Initial commit for Scheduler

### PR DESCRIPTION
**Pull request by style95**
This is an initial commit for the new core component, "the scheduler".

This is a base branch and it should not be merged until all dependent modules are integrated into this PR. I and my colleagues will open separate PRs to add all dependent modules. They need to be merged into this PR with proper reviews from committers.

### CODE REVIEW

**Comment by style95** [comment]
We will implement modules based on the order defined in this page and add design documents under the page as well:
https://cwiki.apache.org/confluence/display/OPENWHISK/Component+Design

I added the first component design document for the "scheduler" component.
https://cwiki.apache.org/confluence/display/OPENWHISK/Scheduler

Please also refer to this integration plan proposal:
https://cwiki.apache.org/confluence/display/OPENWHISK/Integration+Plan+Proposal

Since this PR would become a huge one and will include many modules, I proposed the plan to integrate it.

**Comment by style95** [comment]
I created a new label, "scheduler".
All PRs which are dependent on this PR will be labeled with it.

So it is supposed to not to merge PRs labeled with "scheduler" directly into the master branch.

**Comment by style95** [comment]
Since this PR will be used as an intermediate PR to merge subsequent PRs into this, I added this branch in upstream repo instead of creating this PR from my forked-repo branch.

Other guys will open PRs against to this PR.

**Comment by markusthoemmes** [comment]
@style95 I'm not quite sure why we need an "official" branch for this feature in the repo itself. We have never done that to date. Can you not work on this feature on a fork and incrementally merge the bits into master? Merging this once it's done into master is kinda impractical anyway.

**Comment by style95** [comment]
@markusthoemmes Thank you for the feedback, I wanted this kind of thing.

Yes, I have thought a few ways to include this kind of big change.
If we agree to accept some components which are not being used in any place at some point, I am happy to do that way.

But I couldn't see much difference.
For example, if I have 18 modules and am willing to contribute all of them with separate PRs(based on the assumption we accept unused codes), reviewers will review each of them and merge them into the master.

And if we have one base branch and merge 18 PRs into the branch one by one, reviewers will also review each of them but just merge them into the base branch instead of the master branch.

We can just avoid the unused codes with the later.

**Comment by markusthoemmes** [comment]
Well if you do it the latter way, you'll have a huge chunk to merge at some point anyway, right?

I'd just push it all to master. That'll ensure it's all continuously tested, non disruptive and everything.

**Comment by style95** [comment]
@markusthoemmes 

I am ok with either way.
I will open a thread in the dev list to form a consensus to keep some unused codes.

Thank you for the suggestion.

**Comment by rabbah** [comment]
+1 for small prs to master.

**Comment by style95** [comment]
@markusthoemmes 
FYI, I removed this branch in the upstream repo.
From now on, I will work on this from the forked branch.

**Pull request closed without merging**
