### PR TITLE
Fixes #3470 - Changed hardcoded timeouts for idle containers and pause grace to config entries

### LINKED ISSUE #3470: Change ContainerProxy `unusedTimeout` and `pauseGrace` from hardcoded defaults to config driven
## Steps to reproduce the issue:

1. Currently, `unusedTimeout` and `pauseGrace` have hardcoded defaults in `ContainerProxy`.
2. This is not ideal.
3. Preferred behavior should be pureconfig entries.

## Additional information you deem important:
* Enhancement, not bug.

### PR DESCRIPTION
**Pull request by bwmcadams**
## Description

Previously, the `idleTimeout` and `pauseGrace` settings for `ContainerProxy` have hardcoded defaults. This code changes to use pureconfig entries, allowing the defaults to be changed in configuration.

Tests have been added to the `ContainerProxyTests` to verify the changes (and config parsing).

## Related issue and scope

- [x] I opened an issue to propose and discuss this change (#3470 )

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [x] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [x] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [x] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [x] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by bwmcadams** [comment]
@markusthoemmes you're probably right on the tests being overkill. Do you want me to update the PR w/o the test block?

**Comment by dubee** [comment]
PG3 2084 ⏳

**Comment by rabbah** [comment]
> @markusthoemmes you're probably right on the tests being overkill. Do you want me to update the PR w/o the test block?

+1

**Comment by bwmcadams** [comment]
config parser tests removed.

**Comment by bwmcadams** [comment]
@dubee "PG3 2084"? I'm not sure if I missed some context or something there.

**Comment by markusthoemmes** [comment]
@bwmcadams I took the liberty to fix the compile error (took the testfile out of the commit).

**Pull request merged**
