### PR TITLE
Use a PoolingConnectionManager even for single connection use-cases.

### PR DESCRIPTION
**Pull request by markusthoemmes**
The PoolingConnectionManager checks connections for their staleness, which is important because we're pausing/resuming containers all the time. Connections can go stale in this process.

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [X] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [X] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [X] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [X] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).

### CODE REVIEW

**Comment by markusthoemmes** [comment]
PG2 3348 🔵

**Comment by chetanmeh** [comment]
Per [mail thread][1] it appeared that plan was to discard the connection post resume and create a fresh one and not go for PoolingConnectionManager approach.  

[1]: https://lists.apache.org/thread.html/6691d334613107d7b2ecdf0caa8ced719b314942149c10f358d98ac6@%3Cdev.openwhisk.apache.org%3E

**Comment by rabbah** [comment]
That’s right - this Pr was basically reverting the previous commit. Implementing the protocol per the mailing list will be a bit more invasive than this Pr.

**Comment by chetanmeh** [comment]
Previous commit enabled use of `PoolingHttpClientConnectionManager` when concurrent request mode was enabled otherwise default connection manager was used. So post this PR we would always be using pooling manager.

So is the understanding correct that its a temporary change and going forward we would implement the approach per mail thread and remove usage of pooling manager?

**Comment by rabbah** [comment]
Yes (that’s my understanding also - based on slack discussion with Markus).

**Comment by markusthoemmes** [comment]
@chetanmeh Yes, that's the idea.

**Pull request merged**
