### PR TITLE
Small Wsk.scala test improvement

### PR DESCRIPTION
**Pull request by satybald**
This a small code improvement PR
* Add try/catch to prevent possible resource leak
* Removed unnecessary braces for string interpolation

### CODE REVIEW

**Comment by rabbah** [comment]
Thanks for the contribution. 
Do you have an Apache cla on file?

**Comment by satybald** [comment]
not yet, I'll do that tomorrow.

**Comment by satybald** [comment]
I've signed a CLA.


>Dear Sayat Satybaldiyev,
> 
> This message acknowledges receipt of your ICLA, which has been filed in the Apache Software Foundation records.
> 
> With this message, the Incubator PMC and the OpenWhisk podling have been notified that your ICLA has been filed. Please contact them with any questions.
> 
> If you have been invited as a committer, please provide the PMC (copied) with your preferred Apache id. The id must be at least three alphanumeric characters starting with an alphabetic character. No special characters.
>

**Comment by rabbah** [comment]
Thanks for your first contribution - looking forward to more goodness.

**Pull request merged**
