### PR TITLE
Introduce jmx for kafka

### PR DESCRIPTION
**Pull request by ningyougang**
- jmx is already introduced into controller and invoker, in the actual
  scene, we not only collect kafka producer and consumer metrics but also
  collect kafka server metrics. So it is necessary to introduce jmx for
  kakfa also.
- Fix bug:jmx support for controller/invoker

## Related issue and scope

~~- [ ] I opened an issue to propose and discuss this change (#????)~~

## My changes affect the following components

- [ ] API
- [ ] Controller
- [x] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [x] Bug fix (jmx support for invoker/controller).
- [x] Enhancement or new feature (introduce jmx support for kafka).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
~~- [ ] I added tests to cover my changes.~~
~~- [ ] My changes require further changes to the documentation.~~
~~- [ ] I updated the documentation where necessary.~~

### CODE REVIEW

**Comment by ningyougang** [comment]
How strange, in my local building env, don't export below error
```
/root/jmxremote.password\nError: Password file not readable: /root/jmxremote.password\nError: Password file not readable: 
```
I use below ansible task to make the files's permission is right
```
- name: copy jmxremote password file
  when: jmx.enabled
  template:
    src: "jmxremote.password.j2"
    dest: "{{ kafka.confdir }}/kafka{{ groups['kafkas'].index(inventory_hostname) }}/jmxremote.password"
    mode: 0600

- name: copy jmxremote access file
  when: jmx.enabled
  template:
    src: "jmxremote.access.j2"
    dest: "{{ kafka.confdir }}/kafka{{ groups['kafkas'].index(inventory_hostname) }}/jmxremote.access"
    mode: 0600
```

I don't why `travis-ci` exported the `/root/jmxremote.password\nError: Password file not readable` error

**Comment by ningyougang** [comment]
Any suggestion?

**Comment by mhenke1** [comment]
@ningyougang 
The reason for your problems is that the uid of the root user on the vm (where Ansible does work) and the uid of the root user inside the container (which is used at runtime) are different . 
So setting the access rights in Ansible does not work. 
For the same reason setting the access rights  of a mounted file system does not work 
when issued from the container.

We encountered the same problem with containers and invokers. 
Our solution was to write a container startup script (`open/common/scala/copyJMXFiles.sh`) 
which copies the jmx related files into the container filesystem and changes a the access rights afterwards.

**Comment by ningyougang** [comment]
thanks.
regarding `controller/invoker`, when build, will copy `copyJMXFiles.sh` to controller/invoker's image.
but regarding `kafka`, because the image is not controller by us, so it seems can't copy `CopyJMXFiles.sh` to `kafka`

Any good idea to solve the problem?

**Comment by ningyougang** [comment]
Closed

**Pull request closed without merging**
