### PR TITLE
Fix invokerId assignment path in zookeeper

### LINKED ISSUE #3856: Invoker id assignment path in zookeeper uses wrong id format
`Invoker` supports using zookeeper for id assignment logic. There it constructs the a path like `/invokers/idAssignment/mapping/<invokerName>`. Due to. the way name is constructed its coming out to be like `/invokers/idAssignment/mapping/Some(10.66.20.10)`. Here invoker was launched with ip as the name.

image

Above is the state as seen via exhibitor. This happens because invokerName below is an `Option`

https://github.com/apache/incubator-openwhisk/blob/9c05de4494d6edbd198fd494d458b908bbc0cd0a/core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala#L133

### PR DESCRIPTION
**Pull request by chetanmeh**
Fixes #3856 

## Description
This PR fixes the id assignment path and also add some tests based on [Curator Test Support](https://curator.apache.org/curator-test/). To enable test some refactoring was done to extract the existing id assignment logic to a new class `InstanceIdAssigner`. 

Going forward this would also simplify work for #3858

## Related issue and scope

- [x] I opened an issue to propose and discuss this change (#3856)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [x] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [x] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [x] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by chetanmeh** [comment]
Note that this would be a backward incompatible change as the path used in zookeeper would get modified. So for any existing setups the id calculation would result in a different result

**Comment by dgrove-oss** [comment]
manually confirmed it works as expected on kube (not checked by travis).  Will merge as soon as PG completes.

**Comment by dgrove-oss** [comment]
@chetanmeh -- would you mind rebasing this to latest master?  We need the reorg of the ansible db variables in #3867 to be in this PR for the PG testing to go through.  Thanks for your patience.

**Comment by chetanmeh** [comment]
Rebased to lasted master

**Comment by dgrove-oss** [comment]
PG3 2525 🏃

**Comment by markusthoemmes** [comment]
Sorry this conflicted with @vvraskin's change, which I merged this morning 😢

**Comment by chetanmeh** [comment]
Rebased to resolve conflicts

**Comment by dgrove-oss** [comment]
PG3 2526 🏃

**Comment by dgrove-oss** [comment]
PG3 2526 👍

**Pull request merged**
