### PR TITLE
Enable test reports for Jenkins build

### PR DESCRIPTION
**Pull request by chetanmeh**
Enables test reports and gradle build scan for Jenkins build  

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [ ] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [ ] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/OpenWhisk-Playground/70/

**Comment by chetanmeh** [comment]
Seems like Jenkins build would not pickup changes in `Jenkinsfile` from a PR ([thread][1]) unless the PR is from a trusted source. For this PR that should have worked though.

@houshengbo Any way to test any change in Jenkins pipeline config?

[1]: https://support.cloudbees.com/hc/en-us/articles/227246367-Why-Jenkinsfile-changes-Are-Not-Reflected-in-PR-Build

**Comment by houshengbo** [comment]
@chetanmeh I am currently verifying this changes to see if the test report is generated in the end.

**Comment by houshengbo** [comment]
@chetanmeh This change does not work as expected. Still no test report was generated. I am also thinking of how to add the test result after the pipeline runs. Do you need to add more maven support?

**Comment by chetanmeh** [comment]
Still new with the pipeline stuff. Would create a local one to test and understand it better!

> We are using scripted pipeline instead of declarative pipeline in jenkinsfile

From [this thread][1] I thought its fine to mix both in same. May be only one was mixing is supported which is to use script within declarative. Not sure on other way around

Can we use declarative and then use `script` for our custom stuff? I see lots of out of the box good steps with declarative support which would be tricky to use in above way

[1]: https://jenkinsci-users.narkive.com/j2IvGy3N/mixing-declarative-and-scripted-pipeline-syntax-in-one-jenkinsfile

**Comment by houshengbo** [comment]
@chetanmeh I have fixed this issue in this PR: https://github.com/apache/incubator-openwhisk/pull/4391

**Comment by chetanmeh** [comment]
The test results are now getting collected and reported at https://builds.apache.org/job/OpenWhisk-Playground/test_results_analyzer/

Thanks @houshengbo !!

**Pull request closed without merging**
