### PR TITLE
Replace JsBoolean(true | false) with JsTrue and JsFalse

### PR DESCRIPTION
**Pull request by satansk**
Resolve issue https://github.com/apache/incubator-openwhisk/issues/4419, replace `JsBoolean(false)` and `JsBoolean(true)` with `JsFalse` and `JsTrue` respectively.

## Related issue and scope

- [x] I opened an issue to propose and discuss this change (#4419)

## My changes affect the following components

- [ ] API
- [x] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [x] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [x] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by markusthoemmes** [comment]
While you're on it, please kill the explicit imports there and always import

```scala
import spray.json._
````
🙏

**Comment by rabbah** [comment]
Awesome @satansk - Thanks for your contribution!

**Comment by rabbah** [comment]
@satansk I took the liberty of rebasing this to master and addressing @markusthoemmes' request.

**Comment by satansk** [comment]
Thank you all @dubee @markusthoemmes and expecially @rabbah , I will take another look at it tonight, because I can't submit PR during my work :)

**Comment by satansk** [comment]
I found that @rabbah has fix the code review issues on my branch, the CI failsure may be an arbitrary failure?

**Pull request merged**
