### PR TITLE
Removed unused controller instances config

### PR DESCRIPTION
**Pull request by chetanmeh**
Current deployments of OpenWhisk have to specify `CONTROLLER_INSTANCES` env variable which per code is not being used in any place. This PR removes this config

## Description

Saw usage of `CONTROLLER_INSTANCE` config in [kube repo](https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/helm/openwhisk/templates/controller-pod.yaml#L141). Upon checking I do not find this config being used in any place. Hence it should be removed such that downstream deployment do not need to specify it anymore

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [ ] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [ ] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by sven-lange-last** [comment]
@chetanmeh would you be ok with keeping this? We are using this setting in our additions to OpenWhisk.

**Comment by chetanmeh** [comment]
@sven-lange-last Are you using this in production code? May be we make it optional then. Currently its marked as required and one needs to provide some value to it which is confusing in setups which do not use this

**Comment by markusthoemmes** [comment]
I agree with @chetanmeh in this case. It's confusing in the context of these deployments.

**Comment by sven-lange-last** [comment]
@chetanmeh @markusthoemmes you are right. That setting is confusing for everybody else and should be removed. Please give me some time to address that...

**Comment by sven-lange-last** [comment]
Sorry for not attending to this PR yet. I was busy with other stuff (#4553, #4520, ...). My understanding is that @mhenke1 also looked into this change...

Will come back soon.

**Pull request merged**
