### PR TITLE
Fix a few compilation accidents

### PR DESCRIPTION
**Pull request by dragos**
This changes make sure the Scala compiler can compile the code base correctly under all circumstances. There are no functional changes in this PR.

## Description
- Add a few explicit types for implicit values that are used before the definition point. This is known to [work only by accident](https://contributors.scala-lang.org/t/implicits-with-inferred-return-type-lead-to-undefined-behavior/615)
- Changed the visibility of an object that also compiles only due to a [bug in the Scala compiler](https://github.com/scala/bug/issues/11554).

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [ ] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by dragos** [comment]
Sorry about the formatting issue. I force-pushed a fix.

**Comment by dragos** [comment]
I have a [few contributions to Apache Spark](https://github.com/apache/spark/pulls?q=is%3Apr+author%3Adragos+is%3Aclosed), but I can't find a confirmation of having signed the CLA, though I'm pretty sure it should be somewhere.

**Comment by rabbah** [comment]
Thanks @dragos and @dotta for these fixes and the background links. For the `Exec` related change, it looks like the offending issue is this reference to the object from outside the `core` package:

https://github.com/apache/incubator-openwhisk/blob/0ffc98352ff87542d4a36cc1e2561bfa8a260784/tests/src/test/scala/actionContainers/ActionContainer.scala#L66

Do you know if there are any other references? (I crudely searched for `Exec.` in `tests)

**Comment by rabbah** [comment]
@dragos sorry it appears we both fixed the formatting error. I restarted the Travis build. I did not find a CLA although this change is small enough that it's fine. For reference I looked here http://people.apache.org/unlistedclas.html and here http://people.apache.org/committer-index.html.

**Comment by dragos** [comment]
Thanks @rabbah! That's indeed the only reference I could find for `Exec`.

**Comment by chetanmeh** [comment]
Thanks @dragos and @dotta for the fixes. Intellij is now all green !!

**Pull request merged**
