### PR TITLE
Bumping to gradle 4

### PR DESCRIPTION
**Pull request by markusthoemmes**
Refer to https://docs.gradle.org/current/release-notes.html for the full release notes.

Notable for OpenWhisk:
- Zinc updated (incremental Scala compiler)
- Better logging for parallel tasks (useful locally when working with `redo`)
- Build cache improvements

### CODE REVIEW

**Comment by csantanapr** [comment]
travis is not passing, rebuilding to see what happens

**Comment by csantanapr** [comment]
@markusthoemmes would be good to update all the repos with the new version of gradle at the same time to have consistency, and have PR open wit Travis passing
- https://github.com/apache/incubator-openwhisk-catalog/blob/master/gradle/wrapper/gradle-wrapper.properties
- https://github.com/apache/incubator-openwhisk-package-cloudant/blob/master/gradle/wrapper/gradle-wrapper.properties
- https://github.com/apache/incubator-openwhisk-package-alarms/blob/master/gradle/wrapper/gradle-wrapper.properties
- https://github.com/apache/incubator-openwhisk-package-kafka/blob/master/gradle/wrapper/gradle-wrapper.properties
- https://github.com/apache/incubator-openwhisk-package-pushnotifications/blob/master/gradle/wrapper/gradle-wrapper.properties

feel free to re-assigned when PR is ready.

cc @jasonpet

**Comment by markusthoemmes** [comment]
@csantanapr 
PG1 1753 🔵 

I'll go ahead and open PRs for the other repos.

**Comment by markusthoemmes** [comment]
@csantanapr all good now 🚀

**Comment by markusthoemmes** [comment]
PG3 1009 🔵 reapproved. @csantanapr can we get to this? I updated all relevant PRs to have Gradle 4.1 which got released meanwhile.

**Pull request merged**
