### PR TITLE
Correct rejection behavior in the multi authentication case

### PR DESCRIPTION
**Pull request by mhenke1**
## Description
The authentication SPI can be used to provides multiple parallel ways to authenticate against Open Whisk by combining different authentication directives (e.g Basic and Bearer authentication).
The unmatched authentication directives (only one directives will match for agiven request) 
are adding additional authentication rejections to the overall list of rejection collected for a given request.
Depending on the evaluation sequence of the additional validation rejections will overshadow meaningful validation rejections following the matched case.
This patch gives those validation rejections priority over the authentication rejections. 
In this way a meaningful error messages are returned to the user. 
An equivalent mechanism is already implemented for content type related rejections.

## Related issue and scope
- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components
- [x] API
- [x] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes
- [x] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:
- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by mhenke1** [comment]
[PG 4|2463 succeeded]

**Comment by rabbah** [comment]
Can you rebased this properly to get rid of the merge commits. 

Can you test this change?

**Comment by mhenke1** [comment]
Rebased

**Comment by mhenke1** [comment]
Since the SPI configured in open only configures Basic authentication only it is not easy to test here
(there will never be a authentication rejection that overshadows an validation rejection).
I have tested this manually to work with the IAM authentication we use in Cloud Functions
(with different authentication sequences and no authentication given)
Additionally it passes our test suite which runs on this configuration.

**Comment by ddragosd** [comment]
@mhenke1 the validation mentioned here is used for AuthZ (authorization) ? 

> Basic and Bearer authentication

**Comment by mhenke1** [comment]
@ddragosd 
validations = our code that implements MiscDirectives.validate 
(mostly checks on a valid entity name format)

IBM Cloud Functions supports the well known Basic authentication using an api key, but also authentication and authorization against IBM IAM by implementing our own authentication and entitlement SPI (Since these enhancements are not usable outside IBM we did not open source these SPIs. But I hope to find time in the near future to explain such a implementation on a example level).

**Comment by mhenke1** [comment]
@rabbah Could you please have another look on this PR. Please see may comments to the test situation above.

**Comment by mhenke1** [comment]
For doumentation purposes:

1) Rejection list if the validation rejection is overshadowed by another configured authetication method

rejections_2spis_bad_full2

This list is reduced to the first rejection only:
rejections_2spis_bad_reduced
 
which is returned as request result
rejections_2spis_bad_result

The fix reduces the list to the ValidationRejection only which is returned correctly
rejections_2spis_good_result

**Pull request merged**
