### PR TITLE
Include rotating user log filename in system logs

### PR DESCRIPTION
**Pull request by dubee**
For debugging purposes, write the rotating log filename `DockerToActivationFileLogStore` uses to system logs.

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [x] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by rabbah** [comment]
This is a different logger then the rest of the system?

**Comment by markusthoemmes** [comment]
@rabbah don't think it is? We switched to `AkkaLogging` (a wrapper of ours) a while ago.

**Comment by rabbah** [comment]
I meant the (new) allocation vs the logger we pass through implicitly... Did we abandon that since components can just create their own?

**Comment by markusthoemmes** [comment]
Ah gotcha, sorry! I think we don't have a hard rule on when to pass and when to create.

**Comment by markusthoemmes** [comment]
Can we include this into #3834? It directly affects the same concerns?

**Pull request merged**
