### PR TITLE
Change the confdir for the default environments.

### PR DESCRIPTION
**Pull request by cbickel**
This makes it much easier to delete all configuration with only one command.

### CODE REVIEW

**Comment by rabbah** [comment]
FWIW we should docker cp the nginx comfy and stop mounting /tmp which has issues for vagrant and reboot where tmp gets wiped.

**Comment by rabbah** [comment]
See https://github.com/apache/incubator-openwhisk/issues/32

**Comment by csantanapr** [comment]
In general /tmp is a bad place to use as a persistent 
Maybe using a different mount point like /$HOME/.openwhisk/edgeconf
This is assuming that when the system reboots and dockers tries to start edge container works to mount the directory

**Comment by cbickel** [comment]
Do you see this as part of this PR?

**Comment by csantanapr** [comment]
Not required for this PR
This PR is a step forward, we can deal with default location or using cp in another PR

I’m not sure on using cp as I don’t understand as it will required for ansible to create container then to de the cp and then do a restart to pickup the new config? How would this trick will be done in docker compose or kube without requiring to build a new image with the config inside
Maybe the nginx supports passing a config string via CMD or env variable?

**Comment by rabbah** [comment]
It’s just a cp no restart or new container.

**Pull request merged**
